### ISSUE TITLE
WordPress and NGINX permissions

### ISSUE THREAD

**Issue by DavidRSW** [servisys/ispconfig_setup#100]
Hi,
I have a problem with the permissions on ISPConfig. With NGINX (only) + MariaDB, WordPress does not have permissions to create the folder uploads and FTP data need to install plugins.

Only works with chmod 777 -R in /var/www/example.com/web.

Does anyone know anything?

**Comment by servisys** [comment]
I think this is releated about how you are running PHP in nginx, not install script related.

**Comment by DavidRSW** [comment]
Thanks for the reply. Yes, it is possible, but php is installed by the script. I have not changed any settings. I have tried to give more permissions but does not work:

chmod 660 /dir/php5-fpm.sock and /web1.sock

I tried it in many VPS but can not find the solution...

**Comment by gOOvER** [comment]
Not install script related.  Sounds like a wrong Owner ;)

**Comment by zenny** [comment]
I guess it is permission related, too.

Just do:

`ls -la  /var/www/example.com`

you will get something like:

`lrwxrwxrwx 1 root root 31 Jan 25  2016 /var/www/example.com -> /var/www/clients/client2/web17/`

Now you know that the example.com's owner is web17 of client2. Therefore, give the user ownership of your WP installation directory:

`chown -R web17:client2 /var/www/example.com/web`

And I guess it would work.

**Comment by servisys** [comment]
Seems ISPConfig related, not the install script..

Inviato da Nexus 6

Il 01 dic 2016 20:10, "zenny" <notifications@github.com> ha scritto:

**Comment by servisys** [comment]
Tested some times, not encoutered this issue.
