### ISSUE TITLE
Can't install ISPConfig on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by TheQuank** [servisys/ispconfig_setup#101]
Welcome to ISPConfig Setup Script v.2.0.2
This software is developed by Temporini Matteo
with the support of the community.
You can visit my website at the followings URLS
http://www.servisys.it http://www.temporini.net
and contact me with the following information
contact email/hangout: temporini.matteo@gmail.com
skype: matteo.temporini
=========================================
ISPConfig 3 System installer
=========================================

This script will do a nearly unattended intallation of
all software needed to run ISPConfig 3.
When this script starts running, it'll keep going all the way
So before you continue, please make sure the following checklist is ok:

- This is a clean standard clean installation for supported systems
- Internet connection is working properly

The detected Linux Distribution is:  Ubuntu 16.04 LTS

Sorry but your System is not supported by this script, if you want your system supported
open an issue on GitHub: https://github.com/servisys/ispconfig_setup

**Comment by GLinBoy** [comment]
I get same error too.

**Comment by servisys** [comment]
No ubuntu 16.04 support for now.
