### ISSUE TITLE
The script should be made ready for Isponfig 3.1

### ISSUE THREAD

**Issue by michieltjuh11** [servisys/ispconfig_setup#106]
Probably not much to do, kinda want an option to chose between current, past and beta(source) versions. As Letsencrypt is super handy (free ssl-cerficates all the way!).
Ispconfig is now beta stage, works well for apache except for a few minor ui bugs.

So for the install script:
 - [x] Option to choose desired ispconfig version, current by default.
 - [x] Let letsencrypt install when choosing the beta version (3.1)
 - [ ] Option to protects everything with ssl profided with letsencrypt /w cronjobs to replace certificates.

 Make documentation for each step ^^.

**Comment by servisys** [comment]
Added choose for version 3.1 :)

Added support for Let's Encrypt

**Comment by michieltjuh11** [comment]
Cool

**Comment by cronner** [comment]
ispconfig 3.1 supports Ubuntu 16.04 LTS, The script should support it too

**Comment by servisys** [comment]
Support added, works fine :)

Need test.
