### ISSUE TITLE
Nginx error after installation on ubuntu 16.04

### ISSUE THREAD

**Issue by schliflo** [servisys/ispconfig_setup#129]
After installation of v2.2.1 on a clean ubuntu 16.04 minimal i get the following error:
`2016/10/02 17:18:07 [crit] 28302#28302: *5 connect() to unix:/var/lib/php7.0-fpm/ispconfig.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php7.0-fpm/ispconfig.sock:", host: "example.com:8080"`

**Comment by carras** [comment]
I think "apt-get -y install php7.0-fpm" would solve your problem.

**Comment by carras** [comment]
https://github.com/servisys/ispconfig_setup/issues/135
