### ISSUE TITLE
Configure DKIM for signing mails

### ISSUE THREAD

**Issue by mehargags** [servisys/ispconfig_setup#13]
Hi,
Can you please also add in your script to install necessary packages to add OpenDKIM and other stuff so that it is enabled inside ISPconfig ?

Thanks

**Comment by gOOvER** [comment]
What's the "other Stuff"?

**Comment by mehargags** [comment]
https://github.com/cmjnisse/sogo-ispconfig
and may be some other stuff I will require down the line

**Comment by servisys** [comment]
I've never used SOGO but it's a lot invasive to ispconfig.

I've to see how it works, for now i'll not integrate that in this script.

I'll try to integrate dkim in amavis should be simple.

On some of my server i've integrated this

http://www.faqforge.com/linux/how-to-enable-dkim-email-signatures-in-amavisd-new-and-ispconfig-3/

**Comment by servisys** [comment]
HI in branch v.1.0.4 look at line 588, you can find (sorry for the cut & paste)

  if [ $CFG_DKIM == "n" ]; then
	mkdir -p /var/db/dkim/
	amavisd-new genrsa /var/db/dkim/$CFG_HOSTNAME_FQDN.key.pem
	echo "\$enable_dkim_verification = 1;"  >> /etc/amavis/conf.d/20-debian_defaults
	echo "\$enable_dkim_signing = 1;"  >> /etc/amavis/conf.d/20-debian_defaults
	echo "dkim_key('$CFG_HOSTNAME_FQDN', 'dkim', '/var/db/dkim/$CFG_HOSTNAME_FQDN.key.pem');"  >> /etc/amavis/conf.d/20-debian_defaults
	echo "@dkim_signature_options_bysender_maps = ({ '.' => { ttl => 21*24*3600, c => 'relaxed/simple' } } );"  >> /etc/amavis/conf.d/20-debian_defaults
	MYNET=`cat /etc/postfix/main.cf | grep "mynetworks =" | sed 's/mynetworks = //'`
	echo "@mynetworks = qw( $MYNET );" >> /etc/amavis/conf.d/20-debian_defaults
	/etc/init.d/amavisd-new restart
  fi

**Comment by servisys** [comment]
Better integration with ispconfig 3.1
