### ISSUE TITLE
Kali unsupported

### ISSUE THREAD

**Issue by comthre3** [servisys/ispconfig_setup#130]
Hello, I tried installing ispconfig on my system, but for some reason im getting stuck in the beggining of the installation. Keep getting the error below. Is there a way to make it work?

> The detected Linux Distribution is:  Kali GNU/Linux Rolling
> 
> Sorry but your System is not supported by this script, if you want your system supported 

Thanks

**Comment by servisys** [comment]
Kali linux is not supported from both ISPconfig itself and ispconfig_setup script.
