### ISSUE TITLE
php7-fpm with nginx installation

### ISSUE THREAD

**Issue by carras** [servisys/ispconfig_setup#135]
I think that php7-fpm should be install with the script.

In my case I was getting 502 error until I did "apt-get -y install php7.0-fpm".

PHP7 come included in Ubuntu 16.04

**Comment by n0v3xx** [comment]
I had the same issue with Ubuntu 16.04.

Your command "apt-get -y install php7.0-fpm" fix it.

**Comment by servisys** [comment]
Fixed :)
