### ISSUE TITLE
integrate nGinx

### ISSUE THREAD

**Issue by mehargags** [servisys/ispconfig_setup#14]
I just noticed nGinx is not installed in your script.

Would be much better to have it... and if possible, some settings in ISPConfig to use nGinx in :
1) Apache less, pure nGinx php-fpm mode
2) nGinx as reverse proxy to apache.

I think there are scripts already on Git, you can go through and integrate the same within yours and make it more complete!
Thanks

**Comment by servisys** [comment]
We had integrated nginx in our system, personally don't wanna to use nginx and apache on same server for now.
