### ISSUE TITLE
Repository fails HTTP 404

### ISSUE THREAD

**Issue by gilvandev** [servisys/ispconfig_setup#140]
The repo http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm doesn't exists.
Update to http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm

**Comment by servisys** [comment]
Damn fedora project, hate that distro...

**Comment by gilvandev** [comment]
It's a "wonderful" distro...Debian wins

**Comment by servisys** [comment]
Fixed repository with

http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm

Thank you!
