### ISSUE TITLE
Webmail / roundcube?

### ISSUE THREAD

**Issue by landsman** [servisys/ispconfig_setup#145]
Hi,

install was good. I was create domain, all setup about it and looking for roundcube URL address. 
ISPConfig have link from email account to: https://IP:8080/mail/webmailer.php?id=1 and it is redirected to /webmail but there is just 404.

How can I setup repair this?
log: https://gist.github.com/landsman/fb74e4fd9c7987e04f37e28cfc967f86

thx

**Comment by gOOvER** [comment]
can't see any Errors.

Please, thats not a Support Tracker. When you need Support, please open a Thread at Howto Forge. All your Errors are not really from the Install Script. 

It Seems your Server is not configurated

**Comment by landsman** [comment]
@gOOvER but script should make configuration and this is not working :|

**Comment by gOOvER** [comment]
Thats only apt-get install roundcube.....  so script only execute the command and do not configure Roundcube ;)

**Comment by gOOvER** [comment]
how do you try to open roundcube?

**Comment by landsman** [comment]
@gOOvER RoundCube was installed: https://github.com/servisys/ispconfig_setup/blob/master/distros/debian8/install_webmail.sh#L24

But not working with apache / virtual host.
I try open it just from ISPConfig - click to icon on mail accounts list.

**Comment by landsman** [comment]
omg :) i got it ...
In ISPConfig is bad URL adress redirecting:

Correct url is: http://IP-ADDRESS/webmail/ its :80 port nope :8080

**Comment by gOOvER** [comment]
It's running on Port 80. So what should be fixed?? 

`<VirtualHost *:80>`

**Comment by landsman** [comment]
On my screen is icon with bad link.

**Comment by gOOvER** [comment]
Thats also not part of the install script.  You set tbis link on your own in ispconfig configuration. 

This is,  as i said,  not a Supportforum for ispconfig. 

Please close this ticket

**Comment by landsman** [comment]
Jop, not part of install script, but would be and I don't know where I can change this link in this install script for future ...

**Comment by gOOvER** [comment]
Ok last time i explain: The install script DO NOT change OR set this Path.

You must change this in ispconfig itself. 

If you need Support:

-> https://www.howtoforge.com

**Comment by servisys** [comment]
Not ispconfig related bug.
