### ISSUE TITLE
PHP 7.0

### ISSUE THREAD

**Issue by landsman** [servisys/ispconfig_setup#146]
Hi,

what about PHP version select, v7 support?
Thx

**Comment by gOOvER** [comment]
Only Distro PHP Version is supported by ispconfig. You can compile php7 for your onw. Nothing for install Script

**Comment by jodumont** [comment]
I easily installed PHP7 on Centos7 with REMI like this

> wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
> wget http://rpms.remirepo.net/enterprise/remi-release-7.rpm
> rpm -Uvh remi-release-7.rpm epel-release-latest-7.noarch.rpm
> 
> yum-config-manager --enable remi-php70
> yum update

so just by following the normal steps ;)
https://blog.remirepo.net/post/2016/02/14/Install-PHP-7-on-CentOS-RHEL-Fedora

**Comment by gOOvER** [comment]
I Think, this can be closed. 

For Ubutu/Debian you can use:

**Comment by servisys** [comment]
In Debian 9, we added support for both php 7 and php 5.6
