### ISSUE TITLE
HHVM Debian 8 missing

### ISSUE THREAD

**Issue by degoya** [servisys/ispconfig_setup#154]
the install for HHVM for debian 8 jessie is missing in the dist folder #

**Comment by gOOvER** [comment]
Never add it.  :)  Only added for Ubuntu 16.04

**Comment by degoya** [comment]
the code is included in the install_ispconfigbeta.sh

    echo -e "Installing HHVM"
    sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449
    echo deb http://dl.hhvm.com/debian jessie main | sudo tee /etc/apt/sources.list.d/hhvm.list
    apt-get update
    apt-get -yqq install hhvm

why not as install_hhvm.sh ?

**Comment by servisys** [comment]
Support added :)
