### ISSUE TITLE
[SOLVED] ISPConfig webUI became inaccessible in Debian8 jessie with nginx

### ISSUE THREAD

**Issue by zenny** [servisys/ispconfig_setup#155]
Thanks for such a nice script. Went flawless in debian8 jessie so was in debian7 wheezy.

However, the webUI became inaccessible as 'admin' user as soon as I populated the database from the old server running inside debian wheezy with a very useful script from https://github.com/xavidp/bashscripts/blob/master/migrateispconfig.sh, repeatedly spits out the following error:

> PHP message: PHP Warning:  mysqli_connect(): (28000/1045): Access denied for user 'ispconfig'@'localhost' (using password: YES) in /usr/local/ispconfig/interface/lib/classes/db_mysql.inc.php on line 247" while reading response header from upstream, client: ::1, server: _, request: "GET /js/scrigo.js.php HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php5-fpm/ispconfig.sock:", host: "localhost:8880", referrer: "https://localhost:8880/login/index.php"
> 2016/11/27 19:23:16 [error] 771#771: *3081 FastCGI sent in stderr: "PHP message: PHP Warning:  mysqli_connect(): (28000/1045): Access denied for user 'ispconfig'@'localhost' (using password: YES) in /usr/local/ispconfig/interface/lib/classes/db_mysql.inc.php on line 79

I tried many a solutions I came across online as:
1. update the dbispconfig with a new password for admin
2. `sudo apt-get install --reinstall php5-mysql`
3. Tallied the /usr/local/ispconfig/server/lib/mysql_clientdb.conf with the actual MySQL root password
4. Cleared the browser cache completely and tried with chromium-browser as well as Firefox

In whatsoever case, the 'admin' or any other user can access to the web GUI of ISPConfig.

Thanks in advance!

**Comment by servisys** [comment]
Someone can confirm this?

**Comment by kutmaster** [comment]
If you are yousing MariaDB:
sudo apt-get install install php5-mysqlnd


Check please nginx.conf file for first line `user www-data;`

**Comment by zenny** [comment]
@kutmaster , nope, I am on mysql, fyi.

BTW, the problem is solved. It was fixed by copying  the ispconfig mysql password in /usr/local/ispconfig/{server interface}/lib/config.inc.php from the old server to the new one.

It struck me when ispconfig user could not connect to the dbispconfig DB with the password, created by ispconfig installation script.
