### ISSUE TITLE
Ubuntu 16.10

### ISSUE THREAD

**Issue by dkeister1961** [servisys/ispconfig_setup#158]
Tried using your script, but I get Sorry your system is not supported by this script.
The detected Linux Distribution is: Ubuntu 16.10

I noticed in the check_linux.sh it shows 16.10 but the version ID is 16.04

 #---------------------------------------------------------------------
  #	Ubuntu 16.10
  #---------------------------------------------------------------------

  if echo $ID-$VERSION_ID | grep -iq "ubuntu-16.04"; then
		DISTRO=ubuntu-16.04
fi

**Comment by servisys** [comment]
It's corrected, ubuntu 16.10 not supported yet :)
