### ISSUE TITLE
Letsencrypt not working (Ubuntu 16.04) SOLVED!

### ISSUE THREAD

**Issue by carras** [servisys/ispconfig_setup#161]
Doing a clean install with de script in Ubuntu 16.04 adding new website; then I mark the lets encrypt check box and click save... Why is not working?

How should I do it?

Thanks.

**Comment by gOOvER** [comment]
Can't confirm.  For me it works.

**Comment by gOOvER** [comment]
And Carras: Why my car is not running?

**Comment by carras** [comment]
Do you use nginx?
I go with MariaDB/Nginx. Do you think it does affect?
Why your car runs but not mine? what do you do differently?
I have the port 80 and 443 opens, do I need anything more?
What about the ISPconfig configuration, do you do something before using the lets encrypt feature? Do I need to fill something in the SSL tab before?
Thanks for the help.

**Comment by schliflo** [comment]
Make sure your DNS entry for the domain you want to generate a cert for is correct and at least set for 24h.

**Comment by carras** [comment]
Are you guys using NGINX?

I did change the script deleting "./certbot-auto" and manually I execute "./certbot-auto --nginx". Using that I can manually create the certificates through ssh.

Done this a section in .conf "listen 443 ssl; # managed by Certbot" appear. But if I try to do the lets encrypt function on the ISPconfig GUI it fails and the cert it's not working.

**Comment by carras** [comment]
> Make sure your DNS entry for the domain you want to generate a cert for is correct and at least set for 24h.

You were right. In other to have a certificate to "subdomain.website.com" I made a the DNS of that url and "www.subdomain.website.com" to point to the server too. Then it works.
