### ISSUE TITLE
Debian 8 in lxc container

### ISSUE THREAD

**Issue by cronner** [servisys/ispconfig_setup#162]
ERROR: Stopped: Database already contains some tables.
Restarting web server: apache2 failed!
The apache2 configtest failed. ... (warning).
Output of config test was:
AH00526: Syntax error on line 106 of /etc/apache2/conf-enabled/roundcube.conf:
SSLCertificateFile: file '/usr/local/ispconfig/interface/ssl/ispserver.crt' does not exist or is empty
Action 'configtest' failed.
The Apache error log may have more information.
Well done ISPConfig installed and configured correctly :D 
Now you can connect to your ISPConfig installation at https://koms.dk:8080 or https://IP_ADDRESS:8080
You can visit my GitHub profile at https://github.com/servisys/ispconfig_setup/
You had to edit user/pass /var/lib/roundcube/plugins/ispconfig3_account/config/config.inc.php of roudcube user, as the one you inserted in ISPconfig

using standrd install

**Comment by servisys** [comment]
I'll test every day on lxc container, think not my script related.

**Comment by cronner** [comment]
Was a fresh install using proxmox host and dedicated ip
