### ISSUE TITLE
webmail SSL/vhost

### ISSUE THREAD

**Issue by hkbehari** [servisys/ispconfig_setup#163]
I have used https://github.com/servisys/ispconfig_setup and everything works fine, however when I use SSL on the websites than the https://vhost/webmail/ doesn't work anymore. https://IP_Address/webmail/ does works. Any quick workaround?

**Comment by gOOvER** [comment]
Thats not a problem of this Script. 

What Distro? Which Version?

**Comment by servisys** [comment]
No feedback, probably solved by new versions.
