### ISSUE TITLE
Can't access the ispconfig

### ISSUE THREAD

**Issue by a1phatesters** [servisys/ispconfig_setup#165]
There were few errors while installing ISPconfig, after all process couldn't access ISP config via the port number. It would still show the default page.

Also should have provision for nginx proxy

**Comment by schliflo** [comment]
You probably should at least post the errors that occurred and specify the system you tried to install it on. That's the bare minimum of information someone needs in order to help you...

**Comment by servisys** [comment]
Linux version? Installation type? Cmon guys... we are not wizards...

**Comment by praneetrai** [comment]
Hi,
Same problem here for Debian and Ubuntu.
Went through the standard installation procedure, everthing was ok. Except I got this at the end.
"Restarting apache2 (via systemctl): apache2.service.
sed: can't read /etc/php5/apache2/php.ini: No such file or directory
Well done ISPConfig installed and configured correctly :D"
and accessing the panel through https://IP_ADDRESS:8080

I get the default page of apache.

**Comment by magicbel** [comment]
Same here too :/
Trying on 
-container proxmox with Debian 8 and Ubuntu 15.10
- Vps Scaleway with Debian8

**Comment by gOOvER** [comment]
service apache2 restart
service php7.0-fpm restart

That should fix your problem

**Comment by servisys** [comment]
Pls use always updated distribution... for your security of curse
