### ISSUE TITLE
Add Raspbian Pie Support

### ISSUE THREAD

**Issue by Hirbod** [servisys/ispconfig_setup#167]
Raspbian Pi is fully based on Debian 8 (Jessie).

It identifies itself as Raspbian GNU/Linux 8 (jessie)
There are also older versions (wheezy based ones).

I've patched the install-script after "CheckLinux" and added a hardcoded

DISTRO="debian8" into it. Please consider updating your checking mechanism to support it for Raspberry. Thx!

**Comment by servisys** [comment]
You test? It0s Working with the same scripts of Debian 8?

**Comment by Hirbod** [comment]
It tested, it worked, mostly, but not stable enough to add this by default. Need some more digging but it was a good start.
