### ISSUE TITLE
Layout issue Debian 8

### ISSUE THREAD

**Issue by ianklemm** [servisys/ispconfig_setup#168]
Hi, 

As the picture shows, the layout is broken after customizing the SSL settings.
![ss 2017-01-06 at 01 08 02](https://cloud.githubusercontent.com/assets/13487247/21717467/634e7952-d411-11e6-866e-e9242b05afcd.png)

**Comment by servisys** [comment]
Hi there, yes but only a visualization problem no issue related to this :)

2017-01-06 13:13 GMT+01:00 Vengance <notifications@github.com>:

**Comment by ianklemm** [comment]
yeah, I noticed it later on :)

**Comment by servisys** [comment]
No problem :)
