### ISSUE TITLE
Passwords do not match

### ISSUE THREAD

**Issue by ianklemm** [servisys/ispconfig_setup#169]
Hi, 

I tried the install several times, but I alway get the message, that the admin passwords do not match. 

Sytem: Debian 8

![ss 2017-01-06 at 01 39 08](https://cloud.githubusercontent.com/assets/13487247/21718148/b4304c66-d415-11e6-9992-2ddf81f20681.png)

**Comment by servisys** [comment]
Strange... used lot of times ...

2017-01-06 13:40 GMT+01:00 Vengance <notifications@github.com>:

**Comment by ianklemm** [comment]
I tried the installation like 4 times, always the same issue

**Comment by servisys** [comment]
Someone can confirm issue? For me is working ok.

**Comment by neebs42** [comment]
Having exactly the same issue, running latest debian8 installed from netinstall cd image. Trying a re-install now.

**Comment by mdavou** [comment]
I got same error . Then I left the admin password by default (admin) and got no more problem. Of course the 1st thing I did when install was finished was to change the admin password ... :-)

**Comment by servisys** [comment]
If you leave default password and change after install, all is working.

There's a bug in autmated install of ispconfig, just sollecited on ispconfig bug track.

**Comment by ianklemm** [comment]
So, should I leave the password query in the install script empty?
How can I change the password afterwards?

**Comment by mdavou** [comment]
the default password for the ispconfig admin account is "admin". just enter "Return" and after install, login with the account admin / admin. Once logged in, just change the password.

**Comment by ianklemm** [comment]
When I enter admin/ admin the login page reloads, but nothing happens. 
No error message.

**Comment by mdavou** [comment]
try without password

**Comment by ianklemm** [comment]
Does not work either

**Comment by mdavou** [comment]
No more hints. Sorry. 
Maybe you should re-install on a clean server up to dated

**Comment by servisys** [comment]
I'll try to fix ad soon as possible.

Il 21 gen 2017 17:25, "mdavou" <notifications@github.com> ha scritto:

**Comment by servisys** [comment]
Teste some times after new realse and all is wokring fine

Default user password admin/admin as ispconfig standard
