### ISSUE TITLE
some php5 and mysql5.5 refuse into 16.04 script

### ISSUE THREAD

**Issue by ang3lx** [servisys/ispconfig_setup#170]
I see that into some ubuntu 16.04 there are some apt-get with php5-* call
php5-* is not available on ubuntu 16.04

distros/ubuntu-16.04/install_basics.sh -> 
  apt-get -y install ssh openssh-server vim-nox php5-cli

distros/ubuntu-16.04/install_basephp.sh -> 
  apt-get -yqq install php5-cli php5-mysql php5-mcrypt mcrypt

distros/ubuntu-16.04/install_mysql.sh ->
  mysql-server-5.5 should be mysql-server-5.7 (???)

**Comment by gOOvER** [comment]
i fixed some points

**Comment by servisys** [comment]
Fixed by gOOvER, thank you!
