### ISSUE TITLE
Doesnt work with Debian 9 Squeeze

### ISSUE THREAD

**Issue by bladedshard** [servisys/ispconfig_setup#171]
The detected Linux Distribution is:  Debian GNU/Linux 9 (stretch)

Sorry but your System is not supported by this script, if you want your system supported
open an issue on GitHub: https://github.com/servisys/ispconfig_setup

Please advise, or how can I fix this so I can use this script on my version of debian?

**Comment by servisys** [comment]
Debian 9 not yet released.

Best regards.

**Comment by bladedshard** [comment]
Do you know when it might be released?    As I'm just doing manual install at the moment.
