### ISSUE TITLE
Script stops working ...

### ISSUE THREAD

**Issue by wikrie** [servisys/ispconfig_setup#172]
Hi Everybody,

I try to run the script at Ubuntu 16.04 clean install.
But Script stops working at:

Installing Python packages...
Installation succeeded.
Saving debug log to /var/log/letsencrypt/letsencrypt.log

and nothing happens since 30 min
I check Letsencrypt.log and the last lines were:

017-01-27 21:38:36,983:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin - Beta
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.configurator:ApacheConfigurator
Initialized: <certbot_apache.configurator.ApacheConfigurator object at 0x7ff10f4ff250>
Prep: True
2017-01-27 21:38:36,984:DEBUG:certbot.plugins.selection:Selected authenticator <certbot_apache.configurator.ApacheConfigurator object at 0x7ff10f4ff250> and installer <certbot_apache.configurator.ApacheConfigurator object at 0x7ff10f4ff250>

Can anybody confirm this issue? what did I do wrong? 

br
wikrie

**Comment by wikrie** [comment]
I killed: /root/.local/share/letsencrypt/bin/python2.7 /root/.local/share/letsencrypt/bin/letsencrypt and scripts continue working ...

**Comment by gOOvER** [comment]
Try new script. But wait for my PR, because i added proxy mod

**Comment by mickaelmonsieur** [comment]
I have the same problem today.

**Comment by servisys** [comment]
Fixed.
