### ISSUE TITLE
Bash on Ubuntu on Windows support request

### ISSUE THREAD

**Issue by primedead** [servisys/ispconfig_setup#176]
Hi,

I tried running this on bash. It was able to install it fully but it didn't start in the end. I know bash is still a new thing in beta but there was only an error in the end. I hope maybe you could get it to work. I know these are bash issues but there are workarounds so maybe you can implement them?

This was the last part of the installation:

```
Detect IP addresses
SO_SNDBUF: Invalid argument
Restarting services ...
 * Stopping Postfix Mail Transport Agent postfix
   ...done.
 * Starting Postfix Mail Transport Agent postfix
   ...done.
Stopping amavisd: (not running).
head: cannot open ‘/etc/mailname’ for reading: No such file or directory
  The value of variable $myhostname is "DESKTOP-97LD965", but should have been
  a fully qualified domain name; perhaps uname(3) did not provide such.
  You must explicitly assign a FQDN of this host to variable $myhostname
  in /etc/amavis/conf.d/05-node_id, or fix what uname(3) provides as a host's
  network name!
Starting amavisd: (failed).
 * Stopping ClamAV daemon clamd
   ...done.
 * Starting ClamAV daemon clamd
   ...done.
sh: /etc/init.d/dovecot: No such file or directory
 * Restarting web server apache2
AH00548: NameVirtualHost has no effect and will be removed in the next release /etc/apache2/sites-enabled/000-ispconfig.conf:69
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.1.5. Set the 'ServerName' directive globally to suppress this message
[Fri Feb 03 06:38:07.318677 2017] [core:warn] [pid 5427] (22)Invalid argument: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT
[Fri Feb 03 06:38:07.319178 2017] [core:warn] [pid 5427] (22)Invalid argument: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT
[Fri Feb 03 06:38:07.319178 2017] [core:warn] [pid 5427] (22)Invalid argument: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT
[Fri Feb 03 06:38:07.319178 2017] [core:warn] [pid 5427] (22)Invalid argument: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT
   ...fail!
 * The apache2 instance did not start within 20 seconds. Please read the log files to discover problems
Restarting ftp server: Running: /usr/sbin/pure-ftpd-mysql-virtualchroot -l mysql:/etc/pure-ftpd/db/mysql.conf -l pam -O clf:/var/log/pure-ftpd/transfer.log -b -A -D -H -8 UTF-8 -u 1000 -E -Y 1 -J ALL:!aNULL:!SSLv3 -B
Installation completed.
 * Restarting web server apache2
AH00548: NameVirtualHost has no effect and will be removed in the next release /etc/apache2/sites-enabled/000-ispconfig.conf:69
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.1.5. Set the 'ServerName' directive globally to suppress this message
[Fri Feb 03 06:38:34.318015 2017] [core:warn] [pid 5546] (22)Invalid argument: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT
[Fri Feb 03 06:38:34.318015 2017] [core:warn] [pid 5546] (22)Invalid argument: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT
[Fri Feb 03 06:38:34.318015 2017] [core:warn] [pid 5546] (22)Invalid argument: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT
[Fri Feb 03 06:38:34.318015 2017] [core:warn] [pid 5546] (22)Invalid argument: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT
   ...fail!
```

**Comment by schliflo** [comment]
I don't think it'll be possible to get this working on windows. You might consider using a VM with a supported Linux distribution for that purpose.

**Comment by primedead** [comment]
I installed it yesterday with this: https://msdn.microsoft.com/en-us/commandline/wsl/about . This is a linux distribution on your windows computer. That is where I got that error from. It should be possible with some workarounds (have found a few but not everything). If you had that in mind ignore this message but it wasn't on windows, it was on bash on ubuntu on windows (wsl).

**Comment by servisys** [comment]
Are you fucking kidding me?? :)

Inviato da Nexus 6

Il 03 feb 2017 19:24, "primedead" <notifications@github.com> ha scritto:

**Comment by primedead** [comment]
So I guess that is a I didn't know about and going to check it out?

**Comment by schliflo** [comment]
Ubuntu bash in Windows is definitely not a Linux distribution. It's Microsofts attempt to make some Linux stuff work on Windows. It does not use a Linux kernel whatsoever.
So "Are you fucking kidding me" is an accurate description when getting asked to make something as sophisticated as ispconfig with all its dependencies work on Windows or some broken beta bash emulator experiment or whatever you wanna call it.
So as I stated earlier: it's impossible! ;)

**Comment by primedead** [comment]
Thanks I'm sorry. I'm not known with what it can do and what it can't.

**Comment by servisys** [comment]
Sorry i'll never support windows with this script.

**Comment by servisys** [comment]
I can't sleep ... i think it should work, i've started learning that some days ago, and in the end, bash on Windows is a windows container, so technically this script got to run.

The only dobut about this working is how netwokring work, because in the bash the ip address of the interfaces are the same of windows.. so dunno how networking is managed...

**Comment by schliflo** [comment]
i'm trying this on a fresh windows vm now - for shits and giggles ;)

**Comment by primedead** [comment]
Sorry for keeping you awake I know bash isn't final and that might make it more difficult. There are loads of problems still out there. Thanks for trying it in the first place! I hope you will find an answer. 😄

**Comment by primedead** [comment]
Omg I installed it with the script with a fresh bash install and I was able to login to ispconfig! I still got the same error but it worked in the end. `[Tue May 16 23:17:23.142723 2017] [core:warn] [pid 10125] (92)Protocol not available: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT
[Tue May 16 23:17:23.143079 2017] [core:warn] [pid 10125] (92)Protocol not available: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT
[Tue May 16 23:17:23.143089 2017] [core:warn] [pid 10125] (92)Protocol not available: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT
[Tue May 16 23:17:23.143097 2017] [core:warn] [pid 10125] (92)Protocol not available: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT
   ...done.`

**Comment by schliflo** [comment]
didn't install for me in a fresh vm. which windows version are you using? i thenk the creators update changed a lot of things and fixed a lot of bugs.

**Comment by primedead** [comment]
It looks like that and it failing to connect to bus are the only issues. I am running windows 10 version 1703. I am part of windows insider and put that on slow. so I get updates a little bit faster. I am also not running it in a vm I was running it on my main system.

**Comment by primedead** [comment]
I kind of got it to "work". I wasn't able to login somehow but I was able to get into phpmyadmin. To follow my steps: 
-set up a vm using an iso downloaded with this tool from windows: [https://www.microsoft.com/nl-nl/software-download/windows10](url) 
-enable developer mode and windows subsystem for linux
-run the debian command 
`cd /tmp; wget --no-check-certificate -O installer.tgz "https://github.com/servisys/ispconfig_setup/tarball/master"; tar zxvf installer.tgz; cd *ispconfig*; bash install.sh`
-go to [https://localhost:8080](url)
This just makes sure you have the latest version of bash. It gives some errors (I didn't install the prerequisites) but that somewhat made it work. I did this in a virtualbox machine.

**Comment by finlaywang** [comment]
I have the same problem, but I find out the reason is that I installed wampserver on windows 10 before, so there is already an apache server runing.
So then I stop the wampserver, and start the bash apache server,  it works.

**Comment by russwclark** [comment]
https://windows7bugs.wordpress.com/tag/failed-to-enable-apr_tcp_defer_accept/

**Comment by rehan02** [comment]
Thanks https://github.com/finlaywang, it worked...
