### ISSUE TITLE
Script installwebmail

### ISSUE THREAD

**Issue by xpuska513** [servisys/ispconfig_setup#179]
install.sh: line 152: InstallWebmail: command not found

**Comment by servisys** [comment]
Distro version?

Log?

We are not wizards...

**Comment by xpuska513** [comment]
Distro version: Ubuntu 16.04.2 LTS
Give me a sec and i'll post a log
There is also ClamAV install error:
Updating ClamAV. Please Wait ... ERROR: Problem with internal logger (UpdateLogFile = /var/log/clamav/freshclam.log).
ERROR: /var/log/clamav/freshclam.log is locked by another process

**Comment by servisys** [comment]
Thank you :)

**Comment by xpuska513** [comment]
here is clamav log:
`root@ih360352:/var/log/clamav# cat freshclam.log
Mon Feb 20 11:19:22 2017 -> --------------------------------------
Mon Feb 20 11:19:22 2017 -> freshclam daemon 0.99.2 (OS: linux-gnu, ARCH: x86_64, CPU: x86_64)
Mon Feb 20 11:19:22 2017 -> ClamAV update process started at Mon Feb 20 11:19:22 2017
Mon Feb 20 11:19:52 2017 -> nonblock_connect: connect timing out (30 secs)
Mon Feb 20 11:19:52 2017 -> Can't connect to port 80 of host db.local.clamav.net (IP: 62.181.33.229)
Mon Feb 20 11:19:52 2017 -> Trying host db.local.clamav.net (176.9.33.188)...
Mon Feb 20 11:20:22 2017 -> nonblock_connect: connect timing out (30 secs)
Mon Feb 20 11:20:22 2017 -> Can't connect to port 80 of host db.local.clamav.net (IP: 176.9.33.188)
Mon Feb 20 11:20:22 2017 -> Trying host db.local.clamav.net (194.186.47.19)...
Mon Feb 20 11:20:53 2017 -> Downloading main.cvd [100%]
Mon Feb 20 11:21:08 2017 -> main.cvd updated (version: 57, sigs: 4218790, f-level: 60, builder: amishhammer)
`
About first problem,where i can find install log file?

**Comment by servisys** [comment]
/var/log/ispconfig_setup.log

**Comment by xpuska513** [comment]
Install log:
`Mon Feb 20 11:21:55 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 254: read in ispconfig3.sql
Mon Feb 20 11:21:55 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 898: chmod on mysql-virtual_*.cf*
Mon Feb 20 11:21:55 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 900: chgrp on mysql-virtual_*.cf*
Mon Feb 20 11:21:56 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 904: EXECUTED: groupadd -g 5000 vmail
Mon Feb 20 11:21:56 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 907: EXECUTED: useradd -g vmail -u 5000 vmail -d /var/vmail -m
Mon Feb 20 11:21:56 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e alias_maps = hash:/etc/aliases, hash:/var/lib/mailman/data/aliases
Mon Feb 20 11:21:56 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e alias_database = hash:/etc/aliases, hash:/var/lib/mailman/data/aliases
Mon Feb 20 11:21:56 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e virtual_alias_domains =
Mon Feb 20 11:21:56 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e virtual_alias_maps = hash:/var/lib/mailman/data/virtual-mailman, proxy:mysql:/etc/postfix/mysql-virtual_forwardings.cf, proxy:mysql:/etc/postfix/mysql-virtual_email2email.cf
Mon Feb 20 11:21:56 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e virtual_mailbox_domains = proxy:mysql:/etc/postfix/mysql-virtual_domains.cf
Mon Feb 20 11:21:56 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e virtual_mailbox_maps = proxy:mysql:/etc/postfix/mysql-virtual_mailboxes.cf
Mon Feb 20 11:21:56 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e virtual_mailbox_base = /var/vmail
Mon Feb 20 11:21:56 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e virtual_uid_maps = mysql:/etc/postfix/mysql-virtual_uids.cf
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e virtual_gid_maps = mysql:/etc/postfix/mysql-virtual_gids.cf
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e sender_bcc_maps = proxy:mysql:/etc/postfix/mysql-virtual_outgoing_bcc.cf
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e inet_protocols=all
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e smtpd_sasl_auth_enable = yes
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e broken_sasl_auth_clients = yes
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e smtpd_sasl_authenticated_header = yes
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e smtpd_restriction_classes = greylisting
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e greylisting = check_policy_service inet:127.0.0.1:10023 
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e smtpd_recipient_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination, check_recipient_access mysql:/etc/postfix/mysql-virtual_recipient.cf, reject_rbl_client zen.spamhaus.org
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e smtpd_use_tls = yes
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e smtpd_tls_security_level = may
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e smtpd_tls_cert_file = /etc/postfix/smtpd.cert
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e smtpd_tls_key_file = /etc/postfix/smtpd.key
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e transport_maps = hash:/var/lib/mailman/data/transport-mailman, proxy:mysql:/etc/postfix/mysql-virtual_transports.cf
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e relay_domains = mysql:/etc/postfix/mysql-virtual_relaydomains.cf
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e relay_recipient_maps = mysql:/etc/postfix/mysql-virtual_relayrecipientmaps.cf
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e smtpd_sender_login_maps = proxy:mysql:/etc/postfix/mysql-virtual_sender_login_maps.cf
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e proxy_read_maps = $local_recipient_maps $mydestination $virtual_alias_maps $virtual_alias_domains $sender_bcc_maps $virtual_mailbox_maps $virtual_mailbox_domains $relay_recipient_maps $relay_domains $canonical_maps $sender_canonical_maps $recipient_canonical_maps $relocated_maps $transport_maps $mynetworks $smtpd_sender_login_maps
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e smtpd_helo_required = yes
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e smtpd_helo_restrictions = permit_sasl_authenticated, permit_mynetworks, check_helo_access regexp:/etc/postfix/helo_access, reject_invalid_hostname, reject_non_fqdn_hostname, check_helo_access regexp:/etc/postfix/blacklist_helo
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e smtpd_sender_restrictions = check_sender_access regexp:/etc/postfix/tag_as_originating.re , permit_mynetworks, permit_sasl_authenticated, check_sender_access mysql:/etc/postfix/mysql-virtual_sender.cf, check_sender_access regexp:/etc/postfix/tag_as_foreign.re
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e smtpd_client_restrictions = check_client_access mysql:/etc/postfix/mysql-virtual_client.cf
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e smtpd_client_message_rate_limit = 100
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e maildrop_destination_concurrency_limit = 1
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e maildrop_destination_recipient_limit   = 1
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e virtual_transport = maildrop
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e header_checks = regexp:/etc/postfix/header_checks
Mon Feb 20 11:21:57 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e mime_header_checks = regexp:/etc/postfix/mime_header_checks
Mon Feb 20 11:21:58 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e nested_header_checks = regexp:/etc/postfix/nested_header_checks
Mon Feb 20 11:21:58 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e body_checks = regexp:/etc/postfix/body_checks
Mon Feb 20 11:21:58 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e owner_request_special = no
Mon Feb 20 11:21:58 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e smtp_tls_security_level = may
Mon Feb 20 11:21:58 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3
Mon Feb 20 11:21:58 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e smtpd_tls_protocols = !SSLv2,!SSLv3
Mon Feb 20 11:21:58 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e smtp_tls_protocols = !SSLv2,!SSLv3
Mon Feb 20 11:21:58 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e smtpd_tls_exclude_ciphers = RC4, aNULL
Mon Feb 20 11:21:58 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e smtp_tls_exclude_ciphers = RC4, aNULL
Mon Feb 20 11:21:58 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e myhostname = ih360352.vds.myihor.ru
Mon Feb 20 11:21:58 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e mydestination = ih360352.vds.myihor.ru, localhost, localhost.localdomain
Mon Feb 20 11:21:58 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1003: EXECUTED: postconf -e mynetworks = 127.0.0.0/8 [::1]/128
Mon Feb 20 11:22:00 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1018: EXECUTED: chmod o= /etc/postfix/smtpd.key
Mon Feb 20 11:22:00 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1062: EXECUTED: mkdir /var/vmail/mailfilters
Mon Feb 20 11:22:00 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1067: EXECUTED: chown vmail:vmail /var/vmail/.mailfilter
Mon Feb 20 11:22:00 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1070: EXECUTED: chmod 600 /var/vmail/.mailfilter
Mon Feb 20 11:22:00 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1240: EXECUTED: postconf -e dovecot_destination_recipient_limit = 1
Mon Feb 20 11:22:00 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1240: EXECUTED: postconf -e virtual_transport = dovecot
Mon Feb 20 11:22:00 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1240: EXECUTED: postconf -e smtpd_sasl_type = dovecot
Mon Feb 20 11:22:00 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1240: EXECUTED: postconf -e smtpd_sasl_path = private/auth
Mon Feb 20 11:22:00 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1342: EXECUTED: postconf -e content_filter = amavis:[127.0.0.1]:10024
Mon Feb 20 11:22:00 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1342: EXECUTED: postconf -e receive_override_options = no_address_mappings
Mon Feb 20 11:22:03 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1418: EXECUTED: useradd -d /etc/getmail getmail
Mon Feb 20 11:22:03 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1421: EXECUTED: chown -R getmail /etc/getmail
Mon Feb 20 11:22:03 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1424: EXECUTED: chmod -R 700 /etc/getmail
Mon Feb 20 11:22:04 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1778: EXECUTED: groupadd sshusers
Mon Feb 20 11:22:04 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1947: EXECUTED: groupadd ispapps
Mon Feb 20 11:22:04 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1950: EXECUTED: useradd -g ispapps -d /var/www/apps ispapps
Mon Feb 20 11:22:04 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 1955: EXECUTED: usermod -a -G ispapps www-data
Mon Feb 20 11:22:05 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 2147: EXECUTED: groupadd ispconfig
Mon Feb 20 11:22:05 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 2150: EXECUTED: useradd -g ispconfig -d /usr/local/ispconfig ispconfig
Mon Feb 20 11:22:06 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 2154: EXECUTED: cp -rf ../interface /usr/local/ispconfig
Mon Feb 20 11:22:06 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 2158: EXECUTED: cp -rf ../server /usr/local/ispconfig
Mon Feb 20 11:22:06 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 2165: EXECUTED: cp -rf ../security /usr/local/ispconfig
Mon Feb 20 11:22:06 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 2330: EXECUTED: chown root:root /usr/local/ispconfig
Mon Feb 20 11:22:06 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 2332: EXECUTED: chmod 755 /usr/local/ispconfig
Mon Feb 20 11:22:06 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 2336: EXECUTED: chmod -R 750 /usr/local/ispconfig/interface /usr/local/ispconfig/security /usr/local/ispconfig/server
Mon Feb 20 11:22:06 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 2340: EXECUTED: chown -R ispconfig:ispconfig /usr/local/ispconfig/interface
Mon Feb 20 11:22:06 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 2344: EXECUTED: chown -R root:root /usr/local/ispconfig/server
Mon Feb 20 11:22:06 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 2348: EXECUTED: chown -R root:root /usr/local/ispconfig/security
Mon Feb 20 11:22:06 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 2352: EXECUTED: chown root:ispconfig /usr/local/ispconfig/security/security_settings.ini
Mon Feb 20 11:22:06 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 2354: EXECUTED: chown root:ispconfig /usr/local/ispconfig/security
Mon Feb 20 11:22:06 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 2356: EXECUTED: chown root:ispconfig /usr/local/ispconfig/security/ids.whitelist
Mon Feb 20 11:22:06 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 2358: EXECUTED: chown root:ispconfig /usr/local/ispconfig/security/ids.htmlfield
Mon Feb 20 11:22:06 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 2360: EXECUTED: chown root:ispconfig /usr/local/ispconfig/security/apache_directives.blacklist
Mon Feb 20 11:22:07 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 2420: EXECUTED: adduser www-data ispconfig
Mon Feb 20 11:22:07 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 2423: EXECUTED: adduser www-data ispapps
Mon Feb 20 11:22:07 MSK 2017 - [ISPConfig] - /tmp/ispconfig3_install/install/lib/installer_base.lib.php, Line 2437: EXECUTED: chmod +x /usr/local/ispconfig/server/scripts/create_daily_nginx_access_logs.sh /usr/local/ispconfig/server/scripts/create_jailkit_chroot.sh /usr/local/ispconfig/server/scripts/create_jailkit_programs.sh /usr/local/ispconfig/server/scripts/create_jailkit_user.sh /usr/local/ispconfig/server/scripts/ispconfig_update.sh /usr/local/ispconfig/server/scripts/run-getmail.sh /usr/local/ispconfig/server/scripts/update_from_dev.sh /usr/local/ispconfig/server/scripts/update_from_dev_stable.sh /usr/local/ispconfig/server/scripts/update_from_svn.sh /usr/local/ispconfig/server/scripts/update_stable.sh
`

**Comment by gOOvER** [comment]
webmail is disabled in install script for Ubuntu 16.04, because must be complete rewritten. 

i missed to set a empty function

**Comment by budgierless** [comment]
install.sh: line 153: InstallWebmail: command not found
 **still not fixed for Ubuntu 16.04**

**Comment by ysyukr** [comment]
Ubuntu 16.04 LTS

install.sh: line 153: InstallWebmail: cmmand not found

**Comment by Shad0wGeneral** [comment]
Still not fixed. Getting the same error. Is there some replacement that can be put in its place?

**Comment by daxsmarty** [comment]
i face same error. now what i do??
