### ISSUE TITLE
Add Ubuntu 16.10 support?

### ISSUE THREAD

**Issue by jcsntoll** [servisys/ispconfig_setup#180]
I see the support for 16.10 was planned, but is currently disabled in the Check_linux.sh script.
( defaults to 16.04 ) 
When will full 16.10 support be added?

**Comment by gOOvER** [comment]
when you add it ;) 

why using an non lts vsrsion for server?

**Comment by jcsntoll** [comment]
Well I modified the check_linux.sh script and am installing and testing now.
Shouldn't be that much change between 16.04 and 16.10 just wondered since 16.10 was released back in October and noticed its addition was planned.

Not sure what you mean by "why using an non lts vsrsion for server?"   16.10 is a 64-bit server.
They offer both a desktop and server version.

**Comment by gOOvER** [comment]
in my opinion,  this script should onl,  Support lts Versions.  

Br carefull.  a lot changed at packeges.  Non LTS sjould not be used with a server l.  i see no advantage to use non-lts...  the packages are mostly the same..  no newer php Version,  no support for http/2 in apache

**Comment by servisys** [comment]
It's added, but i'll think the same way as gOOvER, so in future we probably only support LTS versions, lot of work to do for all distribution :)
