### ISSUE TITLE
Errors during install on Turnkey Core fresh install (Debian 8) inside Proxmox LXC

### ISSUE THREAD

**Issue by claflico** [servisys/ispconfig_setup#182]
Just wanted to share some of the errors I got when running the installer on a fresh install of Turnkey Linux core which is based upon Debian 8. I'll do an iso install later and see if the same errors occur. I chose pretty much default for everything.

`/tmp/servisys-ispconfig_setup-6e7b328# bash install.sh
Checking your system, please wait...
install.sh: line 64: /tmp/servisys-ispconfig_setup-6e7b328/distros/debian8/install_metronom.sh: No such file or directory`

`The detected Linux Distribution is:  Debian GNU/Linux 8 (jessie)
Is this correct? (y/n)y
Checking internet connection... cat: /etc/apt/sources.list: No such file or directory
cat: /etc/apt/sources.list: No such file or directory
sed: can't read /etc/apt/sources.list: No such file or directory`

`Installing PureFTPd... Traceback (most recent call last):
  File "/usr/bin/certbot", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python2-pythondialog>=3.2.2rc1' distribution was not found and is required by certbot
Generating a 2048 bit RSA private key`

`Configuring DBServer
Installing ISPConfig crontab
Installing ISPConfig crontab
no crontab for root
no crontab for getmail
Detect IP addresses
Restarting services ...
Failed to get D-Bus connection: Unknown error -1
Failed to get D-Bus connection: Unknown error -1
Failed to get D-Bus connection: Unknown error -1
Failed to get D-Bus connection: Unknown error -1
Failed to get D-Bus connection: Unknown error -1
Installation completed.
Restarting web server: apache2 failed!
The apache2 configtest failed. ... (warning).
Output of config test was:
AH00548: NameVirtualHost has no effect and will be removed in the next release /etc/apache2/sites-enabled/000-ispconfig.conf:69
AH00526: Syntax error on line 61 of /etc/apache2/sites-enabled/000-ispconfig.vhost:
Invalid command 'SSLEngine', perhaps misspelled or defined by a module not included in the server configuration
Action 'configtest' failed.
The Apache error log may have more information.
sed: can't read /etc/php5/apache2/php.ini: No such file or directory`

`tmp/servisys-ispconfig_setup-6e7b328# service apache2 status
[FAIL] apache2 is not running ... failed!`

`/tmp/servisys-ispconfig_setup-6e7b328# uname -r
4.4.35-2-pve`

**Comment by servisys** [comment]
Turnkey not supported.
