### ISSUE TITLE
Debian 9 install don't ask for ispconfig password nor tell user what is it.

### ISSUE THREAD

**Issue by calbasi** [servisys/ispconfig_setup#198]
After installing ispconfig with minor error messages, I get this message:

> Well done ISPConfig installed and configured correctly :D 
> Now you can connect to your ISPConfig installation at https://marti.calbasi.net:8080 or https://IP_ADDRESS:8080

But install script didn't ask me for a ispconfig password, nor tell me that default user/passwd is admin/admin

**Comment by NitroxydeX** [comment]
If you are using the non-expert mode it will not ask for password. You can see it here: https://github.com/servisys/ispconfig_setup/blob/master/distros/debian9/install_ispconfig.sh#L40
The default user in ispconfig is always admin

**Comment by calbasi** [comment]
Well, then I think that password should be prompted, even at non-expert mode (is not an expert/technical question). If not, maybe could be a good idea notice it at readme file to have this info at github project home page. I could do a PR if necessary.

**Comment by servisys** [comment]
No, default password will be admin/admin then you change after install.
