### ISSUE TITLE
Debian 9 install minor error messages

### ISSUE THREAD

**Issue by calbasi** [servisys/ispconfig_setup#199]
While installing in a new server (d9 from an update of an basic d8) I get 2 minor error messages:

> Installing MariaDB... Fix Mysql securityERROR 1396 (HY000) at line 1: Operation DROP USER failed for ''@'localhost'
> ERROR 1396 (HY000) at line 1: Operation DROP USER failed for ''@'marti.calbasi.net'
> ERROR 1008 (HY000) at line 1: Can't drop database 'test'; database doesn't exist
> [DONE]

and

> Updating ClamAV. Please Wait ... ERROR: Problem with internal logger (UpdateLogFile = /var/log/clamav/freshclam.log).
> ERROR: /var/log/clamav/freshclam.log is locked by another process

I don't know if it could be helpful.

**Comment by NitroxydeX** [comment]
The first one shouldn't be a problem. I got it too. Seems that the way the installer handles the installation of mariaDB is different from the normal procedure. That's why it fails.

**Comment by servisys** [comment]
Not a problem, both.

The first will be fixed, no need for that.

The second one simply say log file is locked, if something will fail, will be fixed at next clamav update (wich is already scheduled by default)

**Comment by servisys** [comment]
Removed, no need
