### ISSUE TITLE
postfix master.cf check for wrong values

### ISSUE THREAD

**Issue by NitroxydeX** [servisys/ispconfig_setup#200]
Every check here: https://github.com/servisys/ispconfig_setup/blob/master/distros/debian9/install_postfix.sh#L17 (and maybe on other distros with newest postfix version) will fail and result in not working postfix configurations (e.g. enabling TLS on Port 25 which will result in not accepting anything)

replacement should be:
`sed -i "s/#submission inet n       y       -       -       -       smtpd/submission inet n       y       -       -       -       smtpd/" /etc/postfix/master.cf`

and for all the others too.

postfix chroot by default with 3.1.4

**Comment by servisys** [comment]
Got to check, thank you

**Comment by servisys** [comment]
Fixed
