### ISSUE TITLE
Install-script doesn't check for port

### ISSUE THREAD

**Issue by NitroxydeX** [servisys/ispconfig_setup#201]
https://github.com/servisys/ispconfig_setup/blob/master/install.sh#L174
&
https://github.com/servisys/ispconfig_setup/blob/master/install.sh#L225

has fixed Ports set. If you specify a different port it still shows 8080.

**Comment by servisys** [comment]
Sure, can pass variable from the install script, so this will be default.

If you change port, you know what you are doing :)
