### ISSUE TITLE
Installer repeating "full qualified hostname (fqdn)...: hostname may not be empty" without input

### ISSUE THREAD

**Issue by MattJones76** [servisys/ispconfig_setup#202]
Hi,

I'm running the script on a Debian 8 64bit server. It works flawlessly through all the installations until the initial configuration of ISPConfig3, where it requires inputs to create the MySQL database, at which point it continuously displays:

```
Full qualified hostname (FQDN) of the server, e.g. server1.domain.tld   [ ] :  
Hostname may not be empty
Full qualified hostname (FQDN) of the server, e.g. server1.domain.tld   [ ] : 
Hostname may not be empty
```

it does this over and over without allowing/recognizing any input from my end until I ctrl+c.
This happens regardless of whether I ssh in through the terminal or any remote desktop client.
Here's what it looks like: [http://imgur.com/a/jLOU6](http://imgur.com/a/jLOU6)
Any ideas?

Thank you kindly

![s5qbw7i](https://user-images.githubusercontent.com/30201206/28242402-37db0ac0-6970-11e7-83ed-a9497c4b444b.png)

**Comment by servisys** [comment]
Sme info missing?

In normal install it should not ask for fqdn, you setup you server correctly?

**Comment by MattJones76** [comment]
I believe so, the server is a Debian 64bit fresh install.
Aren't these inputs parts of the process? To build the MySQL database?

```
Full qualified hostname (FQDN) of the server, eg server1.domain.tld  [server1.example.com]:
MySQL server hostname [localhost]: 
MySQL root username [root]: 
MySQL root password []: 
MySQL database to create [dbispconfig]: 
MySQL charset [utf8]:
```

**Comment by servisys** [comment]
No, this is the ispconfig install process called by the script...

**Comment by MattJones76** [comment]
Got it.
Could I send you root access through Skype, and you'll take a look?

**Comment by servisys** [comment]
There's no free support like this, i've already replied va skype.

Thank you.

**Comment by MattJones76** [comment]
Thank you for your time

**Comment by MattJones76** [comment]
I suspect I found the issue, in case anyone else runs into this problem:

type in the command `hostname -f` to display your FQDN as stated in your /etc/hosts file

In my case, upon setting up the VPS this was unspecified--which is why the script kept receiving an empty input.

Set your FQDN as explained here (Debian 8 guide, in my case):
https://www.howtoforge.com/tutorial/perfect-server-debian-8-jessie-apache-bind-dovecot-ispconfig-3/
This guide worked perfectly to complete the install.

**Comment by servisys** [comment]
Following the perfect server setup is mandatory for the script :)

Inviato da Nexus 6

Il 19 ago 2017 00:14, "MattJones76" <notifications@github.com> ha scritto:
