### ISSUE TITLE
Raspberry pi support

### ISSUE THREAD

**Issue by AleksssBoss157** [servisys/ispconfig_setup#204]
It would be awensome if this would work on raspberry pi raspbian 8

**Comment by schliflo** [comment]
This was discussed before in https://github.com/servisys/ispconfig_setup/issues/74 and https://github.com/servisys/ispconfig_setup/issues/167
General consensus seems to be that it would be cool to support raspbian but it's not worth the effort as a raspberry is to slow for properly running ispconfig. However everybody is free to send pull requests ;)
