### ISSUE TITLE
ISPConfig showing default apache page

### ISSUE THREAD

**Issue by arslanshaukat** [servisys/ispconfig_setup#208]
followed all the instructions from here
https://www.howtoforge.com/tutorial/ispconfig-automated-install-script/

 but when I access https://ip:8080/ I get the default apache page. Why is this happening?

**Comment by Monotoba** [comment]
I just provisioned a new vps on host host gator: Ubuntu 16.04.03 and I too have this issue. Ispconfig3 is not set as the default https site on port 8080.

**Comment by Monotoba** [comment]
Turns out that in my case the vps already had apache2 and dovecot installed by default. Using the servi script failed but doing everything manually after removing apache2 and dovecot seems to have worked. I was unable to install quota as that must be done by the host.

**Comment by servisys** [comment]
Nothing had to be installed before the script, if you install something or the vps comes with prinstalled software, you can encounter strange behaviour.
