### ISSUE TITLE
phpmyadmin - dbconfig

### ISSUE THREAD

**Issue by Neustradamus** [servisys/ispconfig_setup#209]
About:
`# - DISABLED DUE TO A BUG IN DBCONFIG - echo "phpmyadmin phpmyadmin/dbconfig-install boolean false" | debconf-set-selections`

Any news, it is resolved?

**Comment by gOOvER** [comment]
where is tge problem to press 2 times Enter? 😁

**Comment by servisys** [comment]
Its a debian bug, not script bug.
