### ISSUE TITLE
PhpMyAdmin and Roundcube displaying source

### ISSUE THREAD

**Issue by marcelobdsilva** [servisys/ispconfig_setup#213]
Hi!

PhpMyAdmin and Roundcube displaying PHP index source code instead of execute the script on Debian 9.
All default options was used.

**Comment by gOOvER** [comment]
The script is not really usefull for Debian9. There are a lot of changes needed

**Comment by marcelobdsilva** [comment]
Oh. Ok. Which is the most recommended?

**Comment by servisys** [comment]
Lol really?

i've used lot of time for debian 9 automation :)

Without logs and error reported all this problem report are unuseful, as i said lot of time in this threads...

**Comment by marcelobdsilva** [comment]
@servisys was you faced this problem any time? All installation occurs very well but webmail and phpmyadmin is displaying source code in screen

**Comment by servisys** [comment]
Try restart apache pls

**Comment by marcelobdsilva** [comment]
Yes. I did it. And reboot server as well.

**Comment by servisys** [comment]
check the log to see if php modules for apache where installed

**Comment by marcelobdsilva** [comment]
php7.0-fpm,  proxy_fcgi, setenvif... all enabled. And if I unzip phpmyadmin on /var/www/html the login screen is displayed correctly. Maybe some ".conf" setup is needed... I'm not comfortable with apache

**Comment by marcelobdsilva** [comment]
Hi!

Just to inform, this "[how to](https://www.howtoforge.com/tutorial/perfect-server-ubuntu-with-nginx-and-ispconfig-3/)" works perfectly for me. And I made a [simple ~maybe dirty~ script](https://github.com/marcelobdsilva/ispconfig) to automate it. 

I think it was not a project issue, but a incompatibility with the VPS's Linux image. So you can close it.

**Comment by servisys** [comment]
Ok, thank you!
