### ISSUE TITLE
Jailkit gives 404

### ISSUE THREAD

**Issue by tmikaeld** [servisys/ispconfig_setup#232]
The link to the Jailkit package now gives a 404 response, thus breaking the install of it since it cannot be installed after Ispconfig.

The broken link:
http://olivier.sessink.nl/jailkit/jailkit-2.19.tar.gz

Should be:
https://olivier.sessink.nl/jailkit/jailkit-2.19.tar.gz

**Comment by jhult** [comment]
Both of those links appear to work for me.
