### ISSUE TITLE
enabling soap by default for remote api to work

### ISSUE THREAD

**Issue by cassini-mohsin** [servisys/ispconfig_setup#234]
I have installed on Debian 9, complete process was very smooth. just need to install this one as well to make it more :)

sudo apt-get install php7.0-soap

**Comment by swarnat** [comment]
+1 
The soap extension is required by the new migration toolkit, too, because they is based on remote API.

**Comment by alie2n** [comment]
I can confirm this. php7.0-soap is required also for the ispconfig3_account plugin of roundcube (which by the way does not work with ispconfig 3.1).
