### ISSUE TITLE
Ubuntu TLS 18.04 is not supported

### ISSUE THREAD

**Issue by alauzon** [servisys/ispconfig_setup#243]
Welcome to ISPConfig Setup Script v.3.0.2
This software is developed by Temporini Matteo
with the support of the community.
You can visit my website at the followings URLs
http://www.servisys.it http://www.temporini.net
and contact me with the following information
contact email/hangout: temporini.matteo@gmail.com
skype: matteo.temporini
=========================================
ISPConfig 3 System installer
=========================================

This script will do a nearly unattended installation of
all software needed to run ISPConfig 3.
When this script starts running, it'll keep going all the way
So before you continue, please make sure the following checklist is ok:

- This is a clean standard clean installation for supported systems
- Internet connection is working properly

The detected Linux Distribution is:  Ubuntu 18.04 LTS

Sorry but your System is not supported by this script, if you want your system supported 
open an issue on GitHub: https://github.com/servisys/ispconfig_setup

**Comment by servisys** [comment]
It's not a bug, it's not supported yet :)

**Comment by alauzon** [comment]
So how do I ask for it to be supported? Because the tool said: "if you want your system supported
open an issue on GitHub: https://github.com/servisys/ispconfig_setup"

**Comment by servisys** [comment]
It's an open project, anyone can work on it :)

**Comment by servisys** [comment]
BTW you're right, i'll take the issue open :)

**Comment by ApertureDevelopment** [comment]
I also would like to request Ubuntu 18.04 Compability

**Comment by Seriusam** [comment]
Yea, I also need it :(

**Comment by jca1981** [comment]
i would like it as well.

**Comment by schliflo** [comment]
https://www.howtoforge.com/tutorial/perfect-server-ubuntu-18-04-nginx-bind-dovecot-and-ispconfig-3/

Could be useful :)

**Comment by erikcas** [comment]
#255

**Comment by servisys** [comment]
Just added 18.04 support, test and report bugs :)

**Comment by olaulau** [comment]
seems to work great, thanks !
