### ISSUE TITLE
Need compatible for Ubuntu 18.04.1 newest

### ISSUE THREAD

**Issue by Wello6143** [servisys/ispconfig_setup#254]
Hi,
Today I can't install ISPConfig because it just support Ubuntu Server 18.04 and down, not 18.04.1. I need ISPConfig support Ubuntu Server 18.04.1.
Thanks

**Comment by erikcas** [comment]
#255 
tested on raspi rpi3B with nginx (I did not check apache yet)

My raspi is a fresh install:

`Welcome to **Ubuntu 18.04.1 LTS** (GNU/Linux 4.15.0-33-generic aarch64)`

**Comment by servisys** [comment]
Just added 18.04 support, test and report bugs :)
