### ISSUE TITLE
Addd Ubuntu 18.04 support

### ISSUE THREAD

**Issue by n0v3xx** [servisys/ispconfig_setup#256]
I got this message:

The detected Linux Distribution is:  Ubuntu 18.04 LTS

Sorry but your System is not supported by this script, if you want your system supported
open an issue on GitHub: https://github.com/servisys/ispconfig_setup

**Comment by erikcas** [comment]
please test pull request #255

**Comment by servisys** [comment]
Just added 18.04 support, test and report bugs :)
