### ISSUE TITLE
ubuntu 18.04 PHP

### ISSUE THREAD

**Issue by olaulau** [servisys/ispconfig_setup#258]
seems that PHP isn't installed properly :
- fastcgi : not working
- FPM : not working
PHP Warning:  file_put_contents(/etc/php/7.2/fpm/pool.d/web27.conf): failed to open stream: No such file or directory in /usr/local/ispconfig/server/lib/classes/system.inc.php on line 839
- suphp : not working
- modphp : not working
- cgi : not working

**Comment by olaulau** [comment]
forcing install of php-fpm, which creates directory /etc/php/7.2/fpm/pool.d , removes the warning but nothing it still doesn't work :

ERROR 403 - Forbidden!
The following error occurred:

You are not permitted to access the requested URL.

Please contact the webmaster with any queries.

**Comment by servisys** [comment]
Got to check so...

**Comment by servisys** [comment]
Just pushed Fixes :)

The only not working is suphp, because not suppoted anymore from ubuntu :)
