### ISSUE TITLE
CentOS 7.5: SELINUX=disabled but script doesnt detect 

### ISSUE THREAD

**Issue by smoonlee** [servisys/ispconfig_setup#260]
Running a fresh install of CentOS 7.5 Minimal on Hyper-V 2012R2 with LIS 4.2
went to run the setup script and get the error even though i've got SELINUX disabled.

The detected Linux Distribution is:     CentOS Linux 7 (Core)
Related Linux Distributions:            rhel fedora
Processor (CPU):                        Intel(R) Xeon(R) CPU E5450 @ 3.00GHz
CPU Cores:                              2
Architecture:                           x86_64 (64-bit)
Total memory (RAM):                     1,827 MiB (1,916 MB)
Total swap space:                       1,019 MiB (1,069 MB)
Computer name:                          HME-LNXCOREWS01
Hostname:                               hme-lnxcorews01.ad.homenetwork.local
IPv4 address:                           x.x.x.x
Time zone:                              Europe/London (BST, +0100)

Virtual Machine (VM) hypervisor:        microsoft

i got around this bug by removing the below from the pre checks sh file

	if [ "$(getsebool 2>&1)" != "getsebool:	SELinux is disabled" ]; then
		sed -i "s/SELINUX=enforcing/SELINUX=disabled/" /etc/selinux/config
		sed -i "s/SELINUX=permissive/SELINUX=disabled/" /etc/selinux/config

		echo -e "\n${red}Attention your SELINUX was enabled, we had modified your configuration.${NC}"
		echo -e "${red}Before restart ISPConfig setup please reboot the server.${NC}"
		echo -e "${red}The script will exit to let you reboot the server${NC}"
		echo "Press Enter to exit"
		read DUMMY
		exit 1
	fi

**Comment by sebruant** [comment]
Change
        if [ "$(getsebool 2>&1)" != "getsebool: SELinux is disabled" ]; then
to:
        if [ "$(getsebool 2>&1)" != "getsebool:  SELinux is disabled" ]; then
