### ISSUE TITLE
nTLD is not accepted as FQDN

### ISSUE THREAD

**Issue by vitushoesl** [servisys/ispconfig_setup#261]
The system does not allow to use a new gTLD as the FQDN.

I have tried using
- ispconfig-test.vh.fyi: does not work
- ispconfig-test.vhso.de: does work

**Comment by servisys** [comment]
Someone tried if this is working with?

RE2='^([[:alnum:]][[:alnum:]\-]{0,61}[[:alnum:]]\.)+[a-zA-Z]{2,63}$'

**Comment by servisys** [comment]
Fixed, do a try if you can :)
