### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by nickrivers** [servisys/ispconfig_setup#268]
I´m trying install ISPConfig with the script but always get stuck in this part:

**Creating config file /etc/dbconfig-common/config with new version
Configurando dbconfig-mysql (2.0.4ubuntu1) ...
Configurando libjs-underscore (1.7.0~dfsg-1ubuntu1) ...
Configurando libjs-sphinxdoc (1.3.6-2ubuntu1.2) ...
Configurando php-phpseclib (2.0.1-1build1) ...
Configurando php-tcpdf (6.0.093+dfsg-1ubuntu1) ...
Configurando phpmyadmin (4:4.5.4.1-2ubuntu2.1) ...root@vps600721:/tmp/servisys-ispconfig_setup-133a52a# aller script at: https://github.com/servisys/ispconfig_setup/issues and with ISPConfig at: https://git.ispconfig.org/ispconfig/**

I´m using Ubuntu 16.04, with 18,04 script stuck too.

**### Server setup:**
The detected Linux Distribution is:	Ubuntu 16.04.5 LTS
Related Linux Distributions:		debian
Processor (CPU):			Intel Core Processor (Haswell, no TSX)
CPU Cores:				1
Architecture:				x86_64 (64-bit)
Total memory (RAM):			3.855 MiB (4.042 MB)
Total swap space:			0 MiB (0 MB)
Graphics Processor (GPU):		Cirrus Logic GD 5446

Any idea ?
<img width="1280" alt="captura de pantalla 2018-10-16 a las 17 46 18" src="https://user-images.githubusercontent.com/3129037/47029700-76868280-d16c-11e8-8742-dddc4afc8ea7.png">

**Comment by tdulcet** [comment]
Are you sure it did not fully install? There is clearly some missing output, but it looks like you got (at least part of) the last line of the script: https://github.com/servisys/ispconfig_setup/blob/133a52a12fa282782c3abf641c3bbb76e6985037/install.sh#L376

Try running `cat /var/log/ispconfig_setup.log` (or opening that file with a text editor) and see if you can see the full log. You may want to try using a different terminal in the future.

**Comment by nickrivers** [comment]
> Are you sure it did not fully install? There is clearly some missing output, but it looks like you got (at least part of) the last line of the script:
> 
> [ispconfig_setup/install.sh](https://github.com/servisys/ispconfig_setup/blob/133a52a12fa282782c3abf641c3bbb76e6985037/install.sh#L376)
> 
> Line 376 in [133a52a](/servisys/ispconfig_setup/commit/133a52a12fa282782c3abf641c3bbb76e6985037)
> 
>  echo "Please report any errors or issues with this auto installer script at: https://github.com/servisys/ispconfig_setup/issues and with ISPConfig at: https://git.ispconfig.org/ispconfig/ispconfig3/issues" 
> Try running `cat /var/log/ispconfig_setup.log` (or opening that file with a text editor) and see if you can see the full log. You may want to try using a different terminal in the future.

Fully install indeed, thanks!
