### ISSUE TITLE
I am getting - fork failed: Cannot allocate memory FATAL -> Failed to fork. What should I do now?

### ISSUE THREAD

**Issue by sarwarcse** [servisys/ispconfig_setup#274]
Preparing to unpack .../13-libhash-merge-perl_0.299-1_all.deb ...
Unpacking libhash-merge-perl (0.299-1) ...
Selecting previously unselected package libclass-method-modifiers-perl.
Preparing to unpack .../14-libclass-method-modifiers-perl_2.12-1_all.deb ...
Unpacking libclass-method-modifiers-perl (2.12-1) ...
Selecting previously unselected package libsub-exporter-progressive-perl.
Preparing to unpack .../15-libsub-exporter-progressive-perl_0.001013-1_all.deb ...
Unpacking libsub-exporter-progressive-perl (0.001013-1) ...
Selecting previously unselected package libdevel-globaldestruction-perl.
Preparing to unpack .../16-libdevel-globaldestruction-perl_0.14-1_all.deb ...
Unpacking libdevel-globaldestruction-perl (0.14-1) ...
Selecting previously unselected package libdynaloader-functions-perl.
Preparing to unpack .../17-libdynaloader-functions-perl_0.003-1_all.deb ...
Unpacking libdynaloader-functions-perl (0.003-1) ...
dpkg: unrecoverable fatal error, aborting:
 fork failed: Cannot allocate memory
FATAL -> Failed to fork.

**Comment by servisys** [comment]
Low memory on vps?

**Comment by sarwarcse** [comment]
now what should I do. Should I start again?
