### ISSUE TITLE
CentOS Su-PHP Missing Module Error

### ISSUE THREAD

**Issue by smoonlee** [servisys/ispconfig_setup#283]
Redirecting to /bin/systemctl status  -l httpd.service
● httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2019-01-07 22:51:53 GMT; 30s ago
     Docs: man:httpd(8)
           man:apachectl(8)
  Process: 14003 ExecStop=/bin/kill -WINCH ${MAINPID} (code=exited, status=1/FAILURE)
  Process: 13743 ExecStart=/usr/sbin/httpd $OPTIONS -DFOREGROUND (code=exited, status=1/FAILURE)
 Main PID: 13743 (code=exited, status=1/FAILURE)

Jan 07 22:51:50 centos-vm.homenetwork.local systemd[1]: Starting The Apache HTTP Server...
Jan 07 22:51:53 centos-vm.homenetwork.local httpd[13743]: httpd: Syntax error on line 353 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/conf.d/suphp.conf: Cannot load /usr/lib64/httpd/modules/mod_suphp.so into server: /usr/lib64/httpd/modules/mod_suphp.so: cannot open shared object file: No such file or directory
Jan 07 22:51:53 centos-vm.homenetwork.local systemd[1]: httpd.service: main process exited, code=exited, status=1/FAILURE
Jan 07 22:51:53 centos-vm.homenetwork.local kill[14003]: kill: cannot find process ""
Jan 07 22:51:53 centos-vm.homenetwork.local systemd[1]: httpd.service: control process exited, code=exited status=1
Jan 07 22:51:53 centos-vm.homenetwork.local systemd[1]: Failed to start The Apache HTTP Server.
Jan 07 22:51:53 centos-vm.homenetwork.local systemd[1]: Unit httpd.service entered failed state.
Jan 07 22:51:53 centos-vm.homenetwork.local systemd[1]: httpd.service failed.

**Comment by smoonlee** [comment]
make[3]: Entering directory `/tmp/suphp-0.7.2/src/apache'
/bin/sh ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../src    -I/usr/include/httpd -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DSUPHP_PATH_TO_SUPHP=\"/usr/sbin/suphp\"  -g -O2 -MT mod_suphp.lo -MD -MP -MF .deps/mod_suphp.Tpo -c -o mod_suphp.lo mod_suphp.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../src -I/usr/include/httpd -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DSUPHP_PATH_TO_SUPHP=\"/usr/sbin/suphp\" -g -O2 -MT mod_suphp.lo -MD -MP -MF .deps/mod_suphp.Tpo -c mod_suphp.c  -fPIC -DPIC -o .libs/mod_suphp.o
In file included from /usr/include/httpd/ap_config.h:25:0,
                 from /usr/include/httpd/httpd.h:44,
                 from mod_suphp.c:24:
/usr/include/httpd/ap_hooks.h:39:17: fatal error: apr.h: No such file or directory
 #include "apr.h"
                 ^
compilation terminated.

![image](https://user-images.githubusercontent.com/22956963/50799219-0dc62680-12d3-11e9-8ba3-34a52b8eb64e.png)

**Comment by smoonlee** [comment]
wget http://suphp.org/download/suphp-0.7.2.tar.gz
tar zxvf suphp-0.7.2.tar.gz
wget -O patchingsuphp.patch https://www.webhostinghero.com/downloads/php/suphp.patch
patch -Np1 -d suphp-0.7.2 < patchingsuphp.patch
cd suphp-0.7.2
autoreconf -if
make
make install

@servisys Tomorrow i'll fork the CentOS Scripts and edit and test and let you know the results. this has fixed the test vm i've got

**Comment by servisys** [comment]
Ok, thank you!

**Comment by smoonlee** [comment]
@servisys - SuPHP Fixed for CentOS - https://github.com/servisys/ispconfig_setup/pull/284
