### ISSUE TITLE
Debian Jessie: suphp missing

### ISSUE THREAD

**Issue by servisys** [servisys/ispconfig_setup#29]
Missing packages in official debian repositories for suphp

**Comment by gOOvER** [comment]
suPHP is not longer maintained

http://www.webhostingtalk.com/showthread.php?t=1270208

**Comment by gOOvER** [comment]
Only for Reminder

apt-get install apache2 apache2.2-common apache2-doc apache2-mpm-prefork apache2-utils libexpat1 ssl-cert libapache2-mod-php5 php5 php5-common php5-gd php5-mysql php5-imap phpmyadmin php5-cli php5-cgi libapache2-mod-fcgid apache2-suexec php-pear php-auth php5-mcrypt mcrypt php5-imagick imagemagick libruby libapache2-mod-python php5-curl php5-intl php5-memcache php5-memcached php5-pspell php5-recode php5-snmp php5-sqlite php5-tidy php5-xmlrpc php5-xsl memcached libapache2-mod-passenger

With this it works

**Comment by gOOvER** [comment]
Can be closed.... SuPHP Support is removed from Jessie Install :)

**Comment by servisys** [comment]
SuPHP Support is removed from Jessie Install
