### ISSUE TITLE
Debian 9 jailkit error during installing

### ISSUE THREAD

**Issue by hardcod3r** [servisys/ispconfig_setup#297]
Hi. I tried several times on a clean debian 9 server.
I follow carefully the guide...
But i got this error
dpkg: error: cannot access archive 'jailkit_2.19-1_*.deb': No such file or directory
Any help please?

**Comment by gOOvER** [comment]
newest version of Jailkit is 2.20

**Comment by gOOvER** [comment]
take a look into /tmp There should be a dir named jailkit-blabla

**Comment by hardcod3r** [comment]
Thank you for your response. Indeed there was a file jailkit but with extension .tgz not deb

**Comment by gOOvER** [comment]
maybe tar is missing on your system. Normally it should be a Dir and this Archive
