### ISSUE TITLE
change option

### ISSUE THREAD

**Issue by fran-pereira** [servisys/ispconfig_setup#306]
Hi friends, 

Congrats on the job, this script has excellent code quality.

I'm currently having trouble choosing another option, whenever I choose webservice nginx the script installs apache

How to check nginx option?

see my screen please http://prntscr.com/om27sx

**Comment by smoonlee** [comment]
I presume you have tried pressing space to select, also what OS and Build Revision are you running?

**Comment by fran-pereira** [comment]
Thanks for the help friend.
