### ISSUE TITLE
Multiserver install on debian don't ask multiserver questions

### ISSUE THREAD

**Issue by szaboistvan373** [servisys/ispconfig_setup#319]
https://github.com/servisys/ispconfig_setup/issues/96#issuecomment-207898450

I followed this comment, but the installer don't ask any questions regarding the multiserver setup.

The installer don't ask these question:
```
setup master
y
```
```
setup mail
n
```
```
setup nameserver
n
```
```
setup database
n
```

So I end up with a normal installation.

**Comment by servisys** [comment]
Wich version of Debian?

**Comment by szaboistvan373** [comment]
Debian 10

**Comment by servisys** [comment]
Not supported on Debian 10,and we don't support this kind of configurations, too complex.

**Comment by tmikaeld** [comment]
@servisys So ispconfig_setup have stopped supporting multi-server setups now?
