### ISSUE TITLE
CentOS 8 support

### ISSUE THREAD

**Issue by Neustradamus** [servisys/ispconfig_setup#320]
CentOS 8 support is missing...

**Comment by mauriziomarini** [comment]
There is no ispconfig perfect server released for CentOS 8, yet, at the date of writing.

**Comment by smoonlee** [comment]
I'm about to test updating my current CentOS 7.6.1810 to version 8, Will let you know how I get on.

**Comment by arvanus** [comment]
If you figure out how to install this packages, say here :)

- dovecot-pigeonhole getmail  postgrey  

other packages secondary: 
webalizer 

- awstats

I've done almost everything, just this are lacking

**Comment by arvanus** [comment]
(yes, you probably could compile they, but I really prefer to use the regular packages  )

**Comment by arvanus** [comment]
Someone kindly shared some the lacking RPMs (have not tested yet)
https://www.howtoforge.com/community/threads/i-need-to-install-ispconfig-on-centos-8.82929/

**Comment by servisys** [comment]
Not offically supported by ispconfig, so don't ask for that.

**Comment by Neustradamus** [comment]
Can you reopen it?

Linked to:
- https://github.com/servisys/ispconfig_setup/issues/344
- https://github.com/servisys/ispconfig_setup/issues/315
- https://github.com/servisys/ispconfig_setup/issues/320
- https://github.com/servisys/ispconfig_setup/issues/334
