### ISSUE TITLE
Raspbian GNU/Linux 10 (buster) not supported

### ISSUE THREAD

**Issue by kfiasche** [servisys/ispconfig_setup#323]
The detected Linux Distribution is:     Raspbian GNU/Linux 10 (buster)
Related Linux Distributions:            debian
Processor (CPU):                        ARMv7 Processor rev 4 (v7l)
CPU Cores:                              4
Architecture:                           arm (32-bit)
Total memory (RAM):                     926 MiB (971 MB)
Total swap space:                       99 MiB (104 MB)
Computer name:                          xxx
Hostname:                               xxx
IPv4 addresses:                         192.168.1.55 192.168.1.56
Time zone:                              Europe/Rome (CET, +0100)

Sorry but your System is not supported by this script, if you want your system supported 
open an issue on GitHub: https://github.com/servisys/ispconfig_setup/issues

It is possible that this script will work if you manually set the DISTRO variable to a version of raspbian that is supported.

**Comment by servisys** [comment]
Raspbian not officiali supported by ISPCONFIG

**Comment by Neustradamus** [comment]
@kfiasche: Have you tested?

It works?
