### ISSUE TITLE
Debian 8 backports moved to archive

### ISSUE THREAD

**Issue by radurambet** [servisys/ispconfig_setup#325]
Debian 8 install adds : ftp.debian.org/debian jessie-backports  in sources list at install time and also roundcube install does this .  For that reason it crashes the install.

Should be updated to archive.debian.org

It is important as multiserver setups may be using debian 8

**Comment by gOOvER** [comment]
Debian 8 have EOL on 30.06.2020. So better use a newer Version of Debian ;)

**Comment by servisys** [comment]
This script is for install ispconfig on new server, so why you wanna install on near EOL systems.

Cmon...
