### ISSUE TITLE
Ubuntu 20.04 is here

### ISSUE THREAD

**Issue by Neustradamus** [servisys/ispconfig_setup#333]
Ubuntu 20.04 is here
- https://ubuntu.com/

**Comment by gOOvER** [comment]
And now? ispconfig3 don't Support it. ;)

**Comment by delphinny** [comment]
Please add support for Ubuntu 20.04 to ISPConfig

**Comment by gOOvER** [comment]
> Please add support for Ubuntu 20.04 to ISPConfig

Wrong Githung ;) This Repro is not ispconfig3 ;) Use Bugtracker of ispconfig3

**Comment by Neustradamus** [comment]
@gOOvER: No, it is to add Ubuntu 20.04 in https://github.com/servisys/ispconfig_setup :)

**Comment by gOOvER** [comment]
> @gOOvER: No, it is to add Ubuntu 20.04 in https://github.com/servisys/ispconfig_setup :)

What do you not understand? 

HE CAN'T ADD AS LONG ISPCONFIG NOT SUPPORT IT !!!!!!!

**Comment by servisys** [comment]
ISPCONFIG DOES'T SUPPORT UBUNTU 20.04

**Comment by Neustradamus** [comment]
Can you reopen it?

Linked to:
- https://github.com/servisys/ispconfig_setup/issues/344
- https://github.com/servisys/ispconfig_setup/issues/333
- https://github.com/servisys/ispconfig_setup/issues/336
