### ISSUE TITLE
Raspbian GNU/Linux 10 (buster)

### ISSUE THREAD

**Issue by Tylerchristensen100** [servisys/ispconfig_setup#345]
The detected Linux Distribution is:     Raspbian GNU/Linux 10 (buster)
Related Linux Distributions:            debian
Processor (CPU):                        ARMv7 Processor rev 4 (v7l)
CPU Cores:                              4
Architecture:                           arm (32-bit)
Total memory (RAM):                     925 MiB (970 MB)
Total swap space:                       99 MiB (104 MB)
Computer name:                          nems.local
Hostname:                               nems.local
IPv4 address:                           192.168.86.134
Time zone:                              America/New_York (EDT, -0400)

Sorry but your System is not supported by this script, if you want your system supported 
open an issue on GitHub: https://github.com/servisys/ispconfig_setup/issues

It is possible that this script will work if you manually set the DISTRO variable to a version of raspbian that is supported.

**Comment by servisys** [comment]
No, because Rapsbian is not offically supported by ispconfig.
