### ISSUE TITLE
ispconfig default admin password (2021)

### ISSUE THREAD

**Issue by iomarian** [servisys/ispconfig_setup#356]
After installing the ispconfig the default admin password is not set to admin :

`The default ISPConfig Username is: admin
              and the Password is: admin
`

for setting the password for admin follow the steps :
Login to the mysql database.

mysql -u root -p
Then enter the password of the mysql root user. To switch to the ISPConfig database, run this command:

use dbispconfig;
And execute the SQL command:

UPDATE sys_user SET passwort = md5('admin') WHERE username = 'admin';
Finally close the mysql shell:

quit;

Hope this helps admins not to scavenge the net for resolution.

**Comment by iomarian** [comment]
glad to help the community .

keep on the good job; many admins rely on your  work  ; #kudos

**Comment by gOOvER** [comment]
Use the official installer. This script is really outdated

**Comment by hsellik** [comment]
@iomarian , thanks. Used this outdated script and made a successful install. Initially, I thought that this was caused by me installing it on a Raspberry Pi 4, but then I noticed this post.

Worked very well.
