### ISSUE TITLE
Request support for Oracle Linux 8.5

### ISSUE THREAD

**Issue by warmech777** [servisys/ispconfig_setup#370]
Hi 
It would be great if you could add support for Oracle Linux 8.5
Thanks

**Comment by gOOvER** [comment]
> 

Ask this on ispconfig3 Forum. As i know, ispconfig3 don't support Oracle Linux.

This script is only for installing supported systems

**Comment by servisys** [comment]
Oracle Linux not supported by ISPConfig.
