### ISSUE TITLE
Installation Options

### ISSUE THREAD

**Issue by nvidian** [servisys/ispconfig_setup#40]
It will be more helpful if there are options for Installation profile of:
- Mail Server
- Web Server
- DNS Server
- Database Server
- Panel Only Server 
Will be great. Also add option for 'Expert' or 'Standard' mode is a must. 

Installation profile will be very useful as one of ISPCONFIG's main feature is multi server setup. 
Thanks anyway for your works. :)

**Comment by Samgarr** [comment]
I would realy like to see support for instalation config files, maybe just premade answers for interactive instalation?

**Comment by servisys** [comment]
We added support for multiserver setup, with this configuration if you only install the master, you can choose what to install :)
