### ISSUE TITLE
Debian 8 - NGINX - 502 Bad Gateway

### ISSUE THREAD

**Issue by nvidian** [servisys/ispconfig_setup#41]
Web server: nginx

I tried to install many times and get the same 502 Bad Gateway result.

Is it related to this https://www.howtoforge.com/community/threads/socket-file-that-ispconfig-references-in-nginx-config-does-not-exist-by-default.66476/ ??

**Comment by gOOvER** [comment]
I never used nginx on Jessie......  So i must see, that i test it. But normally nothing should be changed

**Comment by nvidian** [comment]
Yes, I follow the instructions comment #11 at https://www.howtoforge.com/community/threads/socket-file-that-ispconfig-references-in-nginx-config-does-not-exist-by-default.66476/#post-316980

It fixes the error and now I can login to ISPCONFIG

**Comment by servisys** [comment]
I'll do a check now

**Comment by servisys** [comment]
Sorry but i've tested now and i can.t report any issue.

I can access ISPConfig, access Phpmyad and squirrelmail, and see the default page of apache on nomral http connect.

Can you tell us something else?

**Comment by servisys** [comment]
Unalbe to reacreate error, all working ok.
