### ISSUE TITLE
Use of /etc/os-release for detecting

### ISSUE THREAD

**Issue by gOOvER** [servisys/ispconfig_setup#51]
We should use /etc/os-release for detecting the Distro. So we can remove the use of lsb-release :)

More info's:

http://www.dsm.fordham.edu/cgi-bin/man-cgi.pl?topic=os-release&ampsect=5

**Comment by servisys** [comment]
Yeah, would be much better ;)

**Comment by gOOvER** [comment]
As i see,  is this file present in all Linux Distro's.

**Comment by servisys** [comment]
Fixed
