### ISSUE TITLE
CentOS 7 doesn't work

### ISSUE THREAD

**Issue by kamaxeon** [servisys/ispconfig_setup#59]
Hi,

First that all, thanks for the job.

Script for CentOS7 are using apt, I would like help, but I don't feel comfortable without test.

Have you think any test suite like [shpec](https://github.com/rylnd/shpec) or similar ?

If you want, I can help.

**Comment by servisys** [comment]
Centos is not develeped yet.

**Comment by servisys** [comment]
Under development, right now.

**Comment by servisys** [comment]
p.s.: any help always appreciated :)

**Comment by servisys** [comment]
First implementation relased
