### ISSUE TITLE
Feature: Add hostname setting option

### ISSUE THREAD

**Issue by btoplak** [servisys/ispconfig_setup#61]
Hi @servisys,

congrats, a great job you've done with this script.
I've used it today for the first time, it seems to work very nicely.

## I have a feature suggestion.
The install script currently expects the hostname to be set. I didn't know that and I expected the script to ask me for the hostname and set it up, as done in Perfect Server setups. I think this would be a great addition to the current future set.

Keep up the good work!

**Comment by gOOvER** [comment]
I think the problem would be,  how to know not changing the hostname.  i 
set it up during Server setup and its done at ispconfig3 setup.

Maybe add an Option: Setup Hostname: yes or no


Am 10. August 2015 8:35:00 nachm. schrieb Bernard Toplak 
<notifications@github.com>:

**Comment by servisys** [comment]
Sure we can do in a simple way, but it's less automated then required, as gOOvER said hostname should be already setup before ispconfig, changin hostname may require a reboot, and for now we can't handle that.
