### ISSUE TITLE
ftp server offline issue

### ISSUE THREAD

**Issue by darkworks** [servisys/ispconfig_setup#66]
i  run this script on my new vps two times , but every time same problem  when i go to monitor it says 
myvps have :: debian x64 minimal 
FTP-Server:	Offline

also ftp not working 

i followed it on :: https://www.howtoforge.com/tutorial/ispconfig-install-script-debian/
please fix it thanks

**Comment by servisys** [comment]
Can you please report some error or something else?

Other peple using this script, but not reporting any issue about FTP Server.

I'll do a check in the meanwhile.

**Comment by darkworks** [comment]
i did installation 3rd time but that time i change os from minimal to Debian 7 32 bit 

but same issue  but with little difference i login to panel and went to monitor all services were green running , but now again same ftp server offline   :: http://i.imgur.com/XOvovhf.png

**Comment by darkworks** [comment]
the script installation went smooth no error i got during installation

**Comment by darkworks** [comment]
also my vps is new , so  if you not mind i can provide access to it , so that script is patched and ftp offline server issue is resolved

**Comment by gOOvER** [comment]
I can't confirm. On now 15 till 20 installations with this script, i nver had this Error. Take a look into your Logs. I  hate to see such Bugreports without providing any log. 

I bet you use a bad VPS Template ;)

**Comment by darkworks** [comment]
i have installed Vesta Control panel , and its good now , ftp working no problem

**Comment by gOOvER** [comment]
This is in my Eye's no error of the Install Script..... ;) So this Report can be closed ;)

**Comment by servisys** [comment]
Thank you for confirmation.
