### ISSUE TITLE
Centos 7 webmail

### ISSUE THREAD

**Issue by servisys** [servisys/ispconfig_setup#68]
Adding webmail support squirrelmail or roundcube

**Comment by jodumont** [comment]
I Mister Servisys;
For Christmas
On CentOS
I would like the option to not having a WebMail
:)

Thanks for your beautiful works!

**Comment by jodumont** [comment]
thank for the follow
but I don't understand why we need to choose between desuetude like squirrelmail or roundcube
what's about rainloop ?

**Comment by schliflo** [comment]
not actually resloved. voting to reopen because of https://github.com/servisys/ispconfig_setup/pull/259#issuecomment-423732979
