### ISSUE TITLE
Debian8 webmail link

### ISSUE THREAD

**Issue by hansjess** [servisys/ispconfig_setup#72]
Weblink to squirrelmail does not work. In install_webmail.sh it should be squirrelmail.conf and not just squirrelmail. Thanks for a great script.

**Comment by servisys** [comment]
I'll take a look.

Thank you!

Inviato da Nexus 5
Il 18 ott 2015 00:27, "hansjess" <notifications@github.com> ha scritto:

**Comment by servisys** [comment]
You mean here?

`ln -s /etc/squirrelmail/apache.conf /etc/apache2/conf-enabled/squirrelmail`

**Comment by servisys** [comment]
Fixed.
