### ISSUE TITLE
Debian 8 and MariaDB

### ISSUE THREAD

**Issue by marcolussetti** [servisys/ispconfig_setup#73]
When installing on Debian8, I encounter no issues if I select MySQL, however if I select MariaDB, at the end of the installation, thousands of error messages stating "Unable to connect to MySQL server" appear and the installation does not appear to be successful.

**Comment by servisys** [comment]
I'll take a look, for the problem.

Thank you.

**Comment by servisys** [comment]
This is not an ispconfig issue.

I've tested right now and ispconfig is installed perfeclty.

Here is the log of mariaDB connect

```bash
root@localhost:/tmp/servisys-ispconfig_setup-662fd3e# mysql -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 195
Server version: 10.0.22-MariaDB-0+deb8u1 (Debian)

Copyright (c) 2000, 2015, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> 
```
