### ISSUE TITLE
Support for raspbian ?

### ISSUE THREAD

**Issue by lanaiscool** [servisys/ispconfig_setup#74]
Could u suppory raspbian its based on debian jessy but it says your os is not supported

**Comment by servisys** [comment]
I'll di a check, if packages are alla ready, should be very fast

**Comment by profezzeur** [comment]
Any success ?

**Comment by servisys** [comment]
I want support raspbian, too small to run something like this With good performance.

No One negate ti develop raspbian support and contributo to the project :)

**Comment by FilipStadler** [comment]
I have been using ispconfig on older and slower computers but with limited users ;) 
I have also used til first install script - but the new one does not support my Raspbian GNU/Linux 8 (jessie) this is a great way to lean how to do it with bigger systems anyway the raspbarry 3 is way faster than some of the old servers I have been using ispconfig on.

**Comment by mpathy** [comment]
I cant see how that makes any sense.. ISPconfig is a bit over the top for something like a Raspi..
If you just want to learn about how to use it, install a Virtualbox or something and install a Debian on it and try it there..
They should focus on the three most important server distributions nowaday..

**Comment by servisys** [comment]
No support for Raspberry will be relased. No sense.
