### ISSUE TITLE
Add support for Ubuntu 15.10

### ISSUE THREAD

**Issue by hectorplus** [servisys/ispconfig_setup#77]
File: functions/check_linux.sh
#---------------------------------------------------------------------
#    Ubuntu 15.10
#---------------------------------------------------------------------

  if echo $ID-$VERSION_ID | grep -iq "ubuntu-15.10"; then
                DISTRO=ubuntu15.10
  fi

**Comment by manu777** [comment]
@hectorplus , run the complete install fine on Ubuntu 15.10?

**Comment by servisys** [comment]
Need testing, to know if it works. May be need little changes

**Comment by hectorplus** [comment]
I was able to install it on Ubuntu 15.10, changing version, changing
directory name and so on...working great on my end

**Comment by servisys** [comment]
I'm changin code right now, hope before going sleep to realse support for ubuntu 15.10 (and 14.04)

**Comment by servisys** [comment]
Added, test before production :)
