### ISSUE TITLE
add --no-check-certificate to Wget 

### ISSUE THREAD

**Issue by mehargags** [servisys/ispconfig_setup#8]
You should probably put **--no-check-certificate** in your installation doc, else on a VPS it throws an error for Certificate not valid

**Comment by servisys** [comment]
Mmm normally wget should Not vive errors forma certificate.

I'm testing alla scripts in VMware infrastrutture and got any issue.

Someone report same problem?

**Comment by servisys** [comment]
In any case i can add it ti avoid problems during wget

**Comment by servisys** [comment]
Noneed of --no-check-certificate , all wget are through http and no https.
