### ISSUE TITLE
Debian 8 unary operator

### ISSUE THREAD

**Issue by Pe46dro** [servisys/ispconfig_setup#87]
While i'm using your script on Debian 8 i got an error similar to this:
```log
=: unary operator expected at line 127 installer.sh
```

I think it's a problem with variable `CFG_SETUP_WEB` that seem not initialized

**Comment by Soeldner** [comment]
today:
```
install.sh: line 126: [: ==: unary operator expected
```

**Comment by servisys** [comment]
Relased version 2.0.1: fixed the issue.

Thank you for debug! :+1:
