### ISSUE TITLE
Only squirrelmail

### ISSUE THREAD

**Issue by Pe46dro** [servisys/ispconfig_setup#88]
I saw that code to install roundcube is already implemented but i can't choose it during installation

**Comment by servisys** [comment]
Which distro?

**Comment by Pe46dro** [comment]
Debian 8 Jessie with NGINX

**Comment by SergiX44** [comment]
and also with apache debian 8

**Comment by xagaba** [comment]
Now that roundcube it's in debian 8 backpots repository, will be integrated in the script ?

**Comment by servisys** [comment]
Yes, we will integrate in Debian 8 :)

**Comment by PitbullOL** [comment]
Like this:
https://github.com/PitbullOL/ispconfig_setup/commit/0722b5c7cfaca7157cbfad648066939a8bc2e6b7

**Comment by servisys** [comment]
Fixed in development, soon will be merged in stable.
