### ISSUE TITLE
Ubuntu 15.10 - [: ==: unary operator expected

### ISSUE THREAD

**Issue by n0v3xx** [servisys/ispconfig_setup#92]
Hi,
i got this error with Ubuntu 15.10:

The detected Linux Distribution is:  Ubuntu 15.10

Is this correct? (y/n)y
Checking internet connection...  OK

install.sh: line 119: [: ==: unary operator expected
install.sh: line 122: AskQuestionsMultiserver: command not found
Updating apt and upgrading currently installed packages... [DONE]

/tmp/servisys-ispconfig_setup-b9730ca/distros/ubuntu-15.10/install_mysql.sh: line 6: [: ==: unary operator expected
Installing MariaDB... [DONE]

install.sh: line 126: [: ==: unary operator expected
install.sh: line 126: [: ==: unary operator expected
install.sh: line 137: /tmp/servisys-ispconfig_setup-b9730ca/distros/ubuntu-15.10/install_basephp.sh: No such file or directory
install.sh: line 138: InstallBasePhp: command not found
install.sh: line 140: [: ==: unary operator expected
install.sh: line 140: [: ==: unary operator expected
install.sh: line 145: [: ==: unary operator expected
install.sh: line 145: [: ==: unary operator expected
Installing stats... [DONE]

No PHP MySQL functions available. Please ensure that the PHP MySQL module is loaded./tmp/servisys-ispconfig_setup-b9730ca/distros/ubuntu-15.10/install_ispconfig.sh: line 72: [: ==: unary operator expected
/tmp/servisys-ispconfig_setup-b9730ca/distros/ubuntu-15.10/install_ispconfig.sh: line 75: /etc/init.d/apache2: No such file or directory
/tmp/servisys-ispconfig_setup-b9730ca/distros/ubuntu-15.10/install_fix.sh: line 2: [: ==: unary operator expected
Well done ISPConfig installed and configured correctly :D

**Comment by GAMELASTER** [comment]
Me too..

**Comment by reyvhernandez** [comment]
same here.

**Comment by michieltjuh11** [comment]
There should be no problem though, The : ==: unary operator expected: mean a value is empty,
It comes from the multi-server setup wich you can't/dont use as it is for the installBasePhp command.
Don't know about: "/tmp/servisys-ispconfig_setup-b9730ca/distros/ubuntu-15.10/install_ispconfig.sh: line 75: /etc/init.d/apache2: No such file or directory" but with `service apache2 restart` should be a manual fix.

**Comment by GAMELASTER** [comment]
https://github.com/GAMELASTER/ispconfig_setup
My fork works (old, but tested).
Tested: Debian 7 (8 too I think)

**Comment by erikcas** [comment]
if you donot want to setup multiserver, do prior to executing install.sh
export CFG_MULTISERVER=no

install will succeed

**Comment by servisys** [comment]
I'll do a fix, soon.

**Comment by kayyyy** [comment]
I am getting the Same on Ubuntu 14.04.4

**Comment by Botanistt** [comment]
same with debian 7

**Comment by servisys** [comment]
Fixed issue, i'll relase now versione 2.0.4.
