### ISSUE TITLE
Multi server setup - need guidance

### ISSUE THREAD

**Issue by Getro** [servisys/ispconfig_setup#96]
Hi there,
I need to do multi server setup, but don't know if i need to do the step "How do I get set up? - https://www.howtoforge.com/perfect-server-debian-wheezy-apache2-bind-dovecot-ispconfig-3" on all my 5 servers (web server, db,mail, ns1 & ns2). By the way, i will be using ec2 debian 8. 
Thank you for the help and it's greatly appreciated.

**Comment by michieltjuh11** [comment]
Hi,
This may be a bit late. The ec2 debian shouldnt be posing a problem,
Here the must haves, the other things in the install scriptt should be super straightforward.
Firstly you got to make ready the servers:
#### The only thing you need to perform on the servers to make it ready:
add to '/etc/hosts'
```
<ip of the server>	ns1.example.com	ns1
<ip of the server>	ns2.example.com ns2
<ip of the server>	db.example.com	db
<ip of the server>	mail1.example.com  mail
<ip of the server>	web.example.com web
```
set hostname
`echo panel.ensync.it > /etc/hostname`
restart hostname
`/etc/init.d/hostname.sh`
check hostname is set to FQDN
```
hostname
hostname -f
```
#### Install the web/panel server:
ssh in to your server
`
cd /tmp; wget --no-check-certificate -O installer.tgz "https://github.com/servisys/ispconfig_setup/tarball/master"; tar zxvf installer.tgz; cd *ispconfig*; bash install.sh
`
choose mastermysql pass, remember this!
`<MP>`
setup master
`y`
setup mail
`n`
setup nameserver
`n`
setup database
`n`
select webserver
`apache`

after the installation, log in to either mysql/mariadb through the terminal or via phpmyadmin, if you choose that.
perform for all servers
```
CREATE USER 'root'@'<slave-ip>' IDENTIFIED BY '<SP>'; GRANT ALL PRIVILEGES ON * . * TO 'root'@'<slave-ip>' IDENTIFIED BY '<SP>' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
CREATE USER 'root'@'<slave-FQDN>' IDENTIFIED BY '<SP>; GRANT ALL PRIVILEGES ON * . * TO 'root'@'<slave-FQDN>' IDENTIFIED BY '<SP>' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
```
#### Install a slave server e.g. mail:
`
cd /tmp; wget --no-check-certificate -O installer.tgz "https://github.com/servisys/ispconfig_setup/tarball/master"; tar zxvf installer.tgz; cd *ispconfig*; bash install.sh
`
slave password
`<SP>`
setup master
`n`
master FQDN
`master-FQDN`
master password
`<MP>`
setup web
`n`
setup mail
`y`
setup nameserver
`n`
setup database
`n`

Any more questions hit me up 😉

**Comment by Getro** [comment]
Thank you very much, you are a great help. Stay blessed.

**Comment by michieltjuh11** [comment]
Well because of my lazyness there is no documentation on the multi-server setup >.>

**Comment by al4tb13** [comment]
Hi , i am facing problem setup slave, it will not connect to master . i setup whezzy before with 3 slave and no prob,i think it todo with host name or mariadb or so.can you help?
thanks

**Comment by servisys** [comment]
More details pls.. log something... we are not wizards :)

**Comment by al4tb13** [comment]
not sure about this problem but slave server cant connect to master, also when adding user using sql command i face some error 
CREATE USER 'root'@'<slave-FQDN>' IDENTIFIED BY '<SP>; GRANT ALL PRIVILEGES ON * . * TO 'root'@'<slave-FQDN>' IDENTIFIED BY '<SP>' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
 the first connect run ok. report something todo with mariadb error 1044

this is the screen from slave server error


ry but you cant connect to Master mysql server

     - Check to had run the mysql command to allow remote connection
     - Check FQDN is correct
     - Check root MySQL password is correct

**Comment by servisys** [comment]
You can connect through command line with user, password and fqdn provided ?

2016-05-01 12:29 GMT+02:00 al4tb13 <notifications@github.com>:

> not sure about this problem but slave server cant connect to master, also
> when adding user using sql command i face some error
> CREATE USER 'root'@'' IDENTIFIED BY '; GRANT ALL PRIVILEGES ON * . * TO
> 'root'@'' IDENTIFIED BY '' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0
> MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
> the first connect run ok. report something todo with mariadb error 1044
>
> this is the screen from slave server error
>
> ry but you cant connect to Master mysql server
>
>  - Check to had run the mysql command to allow remote connection
>  - Check FQDN is correct
>  - Check root MySQL password is correct
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/servisys/ispconfig_setup/issues/96#issuecomment-216033333>
>



-- 

Dott. Matteo Temporini

Linux Registered User #553977

http://www.temporini.net


[image: Facebook] <https://www.facebook.com/temporini.net> [image: Twitter]
<https://twitter.com/diablo666> [image: Linkedin]
<http://it.linkedin.com/in/temporini> [image: Instagram]
<http://instagram.com/diablone> [image: Skype]
<http://htmlsig.com/matteo.temporini>

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Company Name is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.

**Comment by al4tb13** [comment]
what command do i run? 
can you help me out?

**Comment by servisys** [comment]
Something like

mysql -u root -p --host=FQDN

2016-05-01 12:42 GMT+02:00 al4tb13 <notifications@github.com>:

> what command do i run?
> can you help me out?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/servisys/ispconfig_setup/issues/96#issuecomment-216033865>
>



-- 

Dott. Matteo Temporini

Linux Registered User #553977

http://www.temporini.net


[image: Facebook] <https://www.facebook.com/temporini.net> [image: Twitter]
<https://twitter.com/diablo666> [image: Linkedin]
<http://it.linkedin.com/in/temporini> [image: Instagram]
<http://instagram.com/diablone> [image: Skype]
<http://htmlsig.com/matteo.temporini>

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Company Name is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.

**Comment by al4tb13** [comment]
i know that mysql port is open do i need ssh for it to work?

**Comment by al4tb13** [comment]
i want to know if password with * can be use. the lasting i have something similar problem

**Comment by servisys** [comment]
no you had to try connect remotely to mysql with mysql -u root -p --host=YOURFQDN

**Comment by servisys** [comment]
What do you mean with "password with *" ?? The asterisk charachter in the password?

**Comment by al4tb13** [comment]
no its not connected, report say you are not allow  to connect to this MariaDB server
error ERROR 1130 (HY000).
it sound like i cant add user?
this is why the second command not going through?

**Comment by al4tb13** [comment]
i mean my sql have * as a charactor in the password

**Comment by al4tb13** [comment]
will you be able to setup 2 slaves server to a master for some fee. please let me know if you can do this for me.let me know how much it will be. thanks for helping

**Comment by michieltjuh11** [comment]
Hi, I did some quick reading.
the users need to be made on the master server prior to installing the setup.

log in to the master server
```sh
ssh <ip of master server>
```
then login to to MariaDB
```sh
mysql -u root -p
```
you will be prompted to fill in your password.

now you should see that you are logged in to mariaDB.
Run these 2 commands:
Remember to replace
 - `<slave-ip>` with your slave server ip addres
 - `<SP>` with the password of the slave servers password for mariadb
 - `<slave-FQDN>` with the FQDN you added to the hosts file `/etc/hosts` with the corresponding IP!
```
CREATE USER 'root'@'<slave-ip>' IDENTIFIED BY '<SP>'; GRANT ALL PRIVILEGES ON * . * TO 'root'@'<slave-ip>' IDENTIFIED BY '<SP>' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
```

```
CREATE USER 'root'@'<slave-FQDN>' IDENTIFIED BY '<SP>; GRANT ALL PRIVILEGES ON * . * TO 'root'@'<slave-FQDN>' IDENTIFIED BY '<SP>' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
```

**Comment by michieltjuh11** [comment]
That should fix the problem... otherwise make a deal with @servisys 😉

**Comment by al4tb13** [comment]
thats what i did, but the second command got errors,
that is the reason why i think is normal sql and maria different, also if my password with the symbol * may have problem?

**Comment by al4tb13** [comment]
cant log in master using ssh from slave. would port change cause problem?
i change to 2134 instead of 22.

**Comment by al4tb13** [comment]
servisys, will you do that tasks for me? and how much will it cost me?

**Comment by michieltjuh11** [comment]
open terminal from your computer then ssh to the master server.
not via the slave server.

**Comment by michieltjuh11** [comment]
just do the quick tutorial from ssh client on your computer wether that is directly from the terminal if your are using unix os like ubuntu or osx. or putty if you are using windows

**Comment by al4tb13** [comment]
i use putty before, setup some servers before, just want to setup master slave replication to replace my Cpanel setup which cost me money every month. if i setup this 2 server i can cacel Cpanel dns servers i am running

**Comment by al4tb13** [comment]
do you have any suggestion to dns setup for master and slave?

**Comment by servisys** [comment]
Yes i can help you, contact me in private pls, i'll do a check.

Inviato da Nexus 5
Il 01 mag 2016 14:54, "al4tb13" <notifications@github.com> ha scritto:

**Comment by al4tb13** [comment]
how do i contact you?
it is late here Australia. so may be let me know when and how to contact you.

**Comment by servisys** [comment]
Write me at temporini.matteo@gmail.com

Inviato da Nexus 5
Il 01 mag 2016 15:55, "al4tb13" <notifications@github.com> ha scritto:

**Comment by tmikaeld** [comment]
This made me curious, is it possible to setup an Ispconfig with multiple masters (with all services) but that use the same main domain (DNS mirrored) ?

**Comment by Malusovium** [comment]
Well there is an option wich you can configure under settings, mirror <master> server.
You should then put it behind the servers behind a loadbalancer. Never tried it though.
It should be possible but cant imagine a use case for it...

**Comment by tmikaeld** [comment]
Hm, the multi-server setup guide doesn't mention any load balancer needed.

What i expected was a master dns (master server) + dns mirroring (slave server) + more slaves.

What I'm uncertain about is if it's possible to have multiple masters (with control panel) or if there has to be one central master server.

**Comment by Malusovium** [comment]
To my knowledge there has to be one master server wich keeps the dns, web, etc mirroring in check.
However https://www.howtoforge.com/community/threads/multiple-control-panel.60518/ this thread showed me wrong.

**Comment by tmikaeld** [comment]
That's what intrigued me here, and it seems like a main DNS zone + secondary zone is possible to have one main domain and many slaves. (just add more secondary zones).

**Comment by Malusovium** [comment]
It seems so yeah :)

**Comment by tmikaeld** [comment]
I posted in the thread, let's see what the expert says ;-)

**Comment by tmikaeld** [comment]
There is actually an issue with multiserver setup as described in this issue:

https://github.com/servisys/ispconfig_setup/issues/192

And also why @Getro cannot continue with the setup.

**Comment by tmikaeld** [comment]
Another problem, the script asks for the MASTERs mysql password in the last step before asking to create permissions on the master mysql, instead of asking for the SLAVE's mysql password.

@Malusovium In your instructions you ask for the SLAVES's password.

**Comment by Neustradamus** [comment]
Any news?
