### ISSUE TITLE
Only ispconfig.org not reachable!?

### ISSUE THREAD

**Issue by zenny** [servisys/ispconfig_setup#97]
Hi,

This is a very odd situation. I can pull with git as well as wget this script, but once it starts it reports that internet connection is unreachable, whereas, in real, it is reachable to do anything except running this script. Any inputs?

```
> Welcome to ISPConfig Setup Script v.2.0.2
> This software is developed by Temporini Matteo
> with the support of the community.
> You can visit my website at the followings URLS
> http://www.servisys.it http://www.temporini.net
> and contact me with the following information
> contact email/hangout: temporini.matteo@gmail.com
> skype: matteo.temporini
> =========================================
> ISPConfig 3 System installer
> =========================================
> 
> This script will do a nearly unattended intallation of
> all software needed to run ISPConfig 3.
> When this script starts running, it'll keep going all the way
> So before you continue, please make sure the following checklist is ok:
> 
> - This is a clean standard clean installation for supported systems
> - Internet connection is working properly
> 
> 
> The detected Linux Distribution is:  Debian GNU/Linux 8 (jessie)
> 
> Is this correct? (y/n)y
> Checking internet connection... root@debian-ispconfig3:~/ispconfig_setup# **ERROR: Couldn't reach www.ispconfig.org, please check your internet connection**
> root@debian-ispconfig3:/tmp/servisys-ispconfig_setup-bf3cb93#
```

My Internet connection works alright to reach other destinations including to fetch this script from github both using git and wget, fyi.

**Comment by servisys** [comment]
Seems your internet connection problem, or ispconfig.org not reachble.

Not script related problem.

**Comment by zenny** [comment]
It is not Internet problem at my end. And this script is to automate ISPConfig, right? In that case the link to the ispconfig.org in this script might have changed! So could be a script problem.

**Comment by servisys** [comment]
The check is simply this.

ping -q -c 3 www.ispconfig.org > /dev/null 2>&1

Never had this problem before...

**Comment by zenny** [comment]
> ping -q -c 3 www.ispconfig.org > /dev/null 2>&1

doesn't give any result. Maybe ispconfig.org has restricted icmp in their firewall?!

**Comment by deepsh4h** [comment]
Thanks! got the same issue while installing on Ubuntu 18.04 Google Cloud Compute Engine. Ping was not installed, so installed it using 

`apt-get install iputils-ping`

and re ran the script.
