### ISSUE TITLE
Can't acced to ISPConfig port 8080

### ISSUE THREAD

**Issue by Vivien69** [servisys/ispconfig_setup#99]
Hello I can't acced to IP:8080 -> ERR_CONNECTION_REFUSED on chrome.
But when I go to my IP I have : "Welcome to nginx!"
I have tryed to allow port 8080 on iptables but it doesn't work.
Need help please

**Comment by Vivien69** [comment]
Ok, so the first time I have lunch your script, I choice nginx and it wasn't installed, the server was working on apache. So I have reinstall the server, I have install nginx before. and after I have lunch the script. And I can't go to ispconfig with port 8080, If I put on nginx config : listen 8080, It don't work.
I'm a beginner on linux so I have no more information to give you.

**Comment by schliflo** [comment]
You don't need to install nginx before running this script as it does it for you.
It's probably best to run this on a clean system, that was freshly installed.

**Comment by Vivien69** [comment]
I retry, so I choose Nginx and I've got Apache finally ! and when I want to do /etc/init.d/nginx start or services nginx start : Failed to start nginx.service: Unit nginx.service failed to load: No such file or directory. And on my IP adresse i've the Apache home page.

**Comment by schliflo** [comment]
please tell us a bit more about your system/setup and post the console output during installation as it's impossible to diagnose the problem without proper information...

**Comment by servisys** [comment]
You need a fresh install, with no packaged installed. No apache2, no Ngnix, nothing.

In the docs we wrote to follo the perfect server setup based on your distribution.

Normally a fresh install, should be ok to run the script without any issue.
